### ISSUE TITLE
How to use tensorrt_llm for V100 16G version

### ISSUE THREAD

**Issue by AndreWanga** [triton-inference-server/tensorrtllm_backend#102]
Our company wants to use TensorRT-LLM to accelerate the ChatGLM2-6B model. Currently, we are using the V100 16GB GPU.
 I quantized the model to int8 based on your instructions. However, when using TritonServer to load the model, an error regarding insufficient VRAM occurred.
 Are there any options available to reduce the VRAM usage while loading the model?

**Comment by byshiue** [comment]
Can you share the scripts you use to build engine and the full log you see?

**Comment by byshiue** [comment]
Can you share the fulll log?

**Comment by AndreWanga** [comment]
I notice you also reply in my another issue of Tensorrt_LLM, so I reply you both here.

1. here is my scripts to build the chatglm2 for single gpu:

`python build.py --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precition int4 --use_inflight_batching `
in addition, "use_inflight_batching" is not supported in original build.py, it will lead to this error: [](https://github.com/NVIDIA/TensorRT-LLM/issues/138)  so I use the modified one, here is the .py modified:

examples/chatglm2-6b/build.py
[build.txt](https://github.com/triton-inference-server/tensorrtllm_backend/files/13315142/build.txt)

/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/chatglm2_6b/model.py
[model.txt](https://github.com/triton-inference-server/tensorrtllm_backend/files/13315161/model.txt)

When I start the tritonserver, it tells me out of memory
![memory_error](https://github.com/triton-inference-server/tensorrtllm_backend/assets/114132971/8a323f1b-dcee-42f3-a504-a34482bbbc8a)


2. here is my scripts to build the chatglm2 for multi gpus:

`python build.py --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precition int4 --use_inflight_batching --world_size 2`
And error occur when I build the engine
![world_size2_error](https://github.com/triton-inference-server/tensorrtllm_backend/assets/114132971/7e2e691f-1b60-43e9-9f8a-f38580a4c3f7)

@byshiue

**Comment by AndreWanga** [comment]
by the way, chatglm2-6B-int4 is just 3g, but why tensorrt_llm nead more than 16g gpu memory? @byshiue

**Comment by byshiue** [comment]
When you don't use `--enable_context_fmha`, attention requires lots of memory to put activation (depending on the problem size). 
And inflight_batching will enable paged attention, which allocated lots of memory for k/v cache at the beginning.

**Comment by AndreWanga** [comment]
> When you don't use `--enable_context_fmha`, attention requires lots of memory to put activation (depending on the problem size). And inflight_batching will enable paged attention, which allocated lots of memory for k/v cache at the beginning.

So, how can I use tensorrt_llm for v100 16GB version?

**Comment by byshiue** [comment]
Can you try using latest main branch and set smaller batch size, input length and output length first?

**Comment by AndreWanga** [comment]
> Can you try using latest main branch and set smaller batch size, input length and output length first?

Thanks for dealing with my issue, I change the config you told me, and the GPU memory goes down to 14GB

**Comment by byshiue** [comment]
Thank you for the update. Close this bug. Feel free to reopen it if needed.
