### ISSUE TITLE
How to know the streaming is finished in model.py ? 

### ISSUE THREAD

**Issue by yoyopdc** [triton-inference-server/tensorrtllm_backend#106]
Hi there:
    I found some problem when I use the inflight batch in CodeLlama and streaming:
    I begin from the example of all_models/inflight_batcher_llm/ and I changed to my own models,  if every time just decode one token, it works well, but some token should be decode together, like if I pass prompt = "def fun(a,b)\n# return the sum of a and b"
the model will return " \n returna+b", if I did not use the stream the model will return "\n return a + b".
    if every time just decode one token, many result will not be right.
    So I use a cache to cache the tokens, but if the streaming is over I will clean the cache But I do not know when the streaming is over.
     I want to know  how to get the finish state in model.py
thank you !

**Comment by pcastonguay** [comment]
Which model.py are you referring to exactly?

With the Triton grpc client, calling `stop_stream()` will only return when the stream is over from server side. So when `stop_stream` returns, you could post-process your tokens.

https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L349C1-L350C44

If you are using a Triton Python backend to make calls to the `tensorrt_llm` model (sometimes called a Python BLS model: https://github.com/triton-inference-server/python_backend#business-logic-scripting), then you would simply loop over the `inference_responses` returned by a call to `inference_request.exec`. The loop will terminate when the server is done sending responses back.

```
      ...
      inference_request = pb_utils.InferenceRequest(
          model_name='tensorrt_llm'
          inputs=[<pb_utils.Tensor object>])
          
      inference_responses = inference_request.exec(decoupled=True)
      
      all_token_ids = [ ]
      
      # This loop will terminate when the stream is over
      for inference_response in inference_responses:
      
          # get new token ids:
          output_ids_tensor = pb_utils.get_output_tensor_by_name(inference_response, "output_ids")
          new_token_ids = postprocess(output_ids_tensor)
          all_token_ids.extend(new_token_ids)
          
      output_text = postprocessor.decode(all_token_ids)
        
```

**Comment by yoyopdc** [comment]
> Which model.py are you referring to exactly?
> 
> With the Triton grpc client, calling `stop_stream()` will only return when the stream is over from server side. So when `stop_stream` returns, you could post-process your tokens.
> 
> https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L349C1-L350C44
> 
> If you are using a Triton Python backend to make calls to the `tensorrt_llm` model (sometimes called a Python BLS model: https://github.com/triton-inference-server/python_backend#business-logic-scripting), then you would simply loop over the `inference_responses` returned by a call to `inference_request.exec`. The loop will terminate when the server is done sending responses back.
> 
> ```
>       ...
>       inference_request = pb_utils.InferenceRequest(
>           model_name='tensorrt_llm'
>           inputs=[<pb_utils.Tensor object>])
>           
>       inference_responses = inference_request.exec(decoupled=True)
>       
>       all_token_ids = [ ]
>       
>       # This loop will terminate when the stream is over
>       for inference_response in inference_responses:
>       
>           # get new token ids:
>           output_ids_tensor = pb_utils.get_output_tensor_by_name(inference_response, "output_ids")
>           new_token_ids = postprocess(output_ids_tensor)
>           all_token_ids.extend(new_token_ids)
>           
>       output_text = postprocessor.decode(all_token_ids)
>         
> ```

Thanks for your answering:
 I use the example, and the code https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/postprocessing/1/model.py
In the case of streaming, in the excute() function in this model.py, a token will be received each time, and then I will detokenize it and response. But many times, some words are composed of several tokens(or many words has prefill token). If I write a cache, then I can solve this problem. But I find that after I add a cache, I don’t know when this streaming will end. As a result, when the next request comes, my cache still has the value of the previous request.

**Comment by pcastonguay** [comment]
Let me follow up with Triton team to know if it's possible to know if a request corresponds to the last response sent from a decoupled model, when using an ensemble model.

The alternative would be to use a Python BLS backend to replace the ensemble model. We have planned this work but don't have an ETA yet.

**Comment by pcastonguay** [comment]
I followed up with the Triton team and currently the postprocessor model cannot tell which request corresponds to the last one emitted by the tensorrt-llm backend. I have made a request to add this feature in Triton. In the mean time, we have started working on a sample Python BLS backend to demonstrate how to accumulate tokens before calling the postprocessor.

**Comment by yoyopdc** [comment]
waiting for your good news，now I‘m using  a self.cache to fix the problem temporary, But I won't use it in any products
```
        if len(self.cache) > 1000:
            self.cache.popitem(last=False)
        # Every Python backend must iterate over everyone of the requests
        # and create a pb_utils.InferenceResponse for each of them.
        for idx, request in enumerate(requests):
            # print(request.request_id())
            req_id = request.request_id()
            if req_id not in self.cache:
                self.cache[req_id] = list()
```
in def _postprocessing(self, tokens_batch, req_id)
```
for beam_tokens in tokens_batch:
           for tokens in beam_tokens:
            #    print("tokens = ", tokens)
               self.cache[req_id].append(tokens[0])
               output = self.tokenizer.decode(self.cache[req_id])
               outputs.append(output)
```

**Comment by yoyopdc** [comment]
> I have implemented a Python BLS backend that can be used to accumulate tokens before calling the postprocessor. See https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm_bls/1/model.py. The accumulation of tokens happens here: https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm_bls/1/model.py#L174-L204
> 
> The `tensorrt_llm_bls` model takes the same inputs/outputs as the ensemble model. It has an optional parameter `accumulate_tokens` that can be set to `true` to accumulate tokens before calling the post-processor. Note that in that case, every response from the model will contain the full output text, as opposed to only the new words.

Hi thanks for quick support,  when I run the main branch I found a problem , how to fix it ?
<img width="1172" alt="Screenshot 2023-12-03 at 9 52 47 PM" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/21274462/bc14a4de-3f6b-49c6-9dce-90478285ed09">
And I try some project which can run in release version , They have the same problem.

**Comment by pcastonguay** [comment]
Just to be clear, this new BLS backend is part of our `main` branch hence not an official feature yet, just wanted to share in case you were blocked.

The error you're seeing seems to be related to the `tensorrt_llm` model and not the new BLS model but without the full logs it's hard to tell. Are you using the Python or C++ `tensorrt_llm` backend? If using the C++ backend, the error could mean that you are missing `/opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so`

**Comment by yoyopdc** [comment]
> Just to be clear, this new BLS model is part of our `main` branch hence not an official feature yet, just wanted to share in case you were blocked.
> 
> The error you're seeing seems to be related to the `tensorrt_llm` model and not the new BLS model but without the full logs it's hard to tell. Are you using the Python or C++ `tensorrt_llm` backend? If using the C++ backend, the error could mean that you are missing `/opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so`

thank you it is work now! And I had tested it!
