### ISSUE TITLE
Triton server failed

### ISSUE THREAD

**Issue by konakov-ds** [triton-inference-server/tensorrtllm_backend#109]
1. Compiled the model with TensorRT-LLM. Everything is fine at this stage
2. Moved the files (lama_float16_tp2_rank0.engine, lama_float16_tp2_rank1.engine, config.json, model.cashe) to the tensorrtllm_backend repository in the folder tensorrtllm_backend/all_models/inflight_batcher_llm/tensorrt_llm/1/, also moved the tokenizer to the folder tensorrtllm_backend/tensorrt_llm/tokenizer
3. Specified settings preprocessing/config.pbtxt - path to tokenizer, the rest as in the manual
4. Started the container - everything is ok
5. Start server python /opt/scripts/launch_triton_server.py --model_repo /all_models/inflight_batcher_llm --world_size 2
 I get errors:
<img width="871" alt="er1" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/67256924/f0a7468b-2394-4cf0-bd07-8bc87ea6d6e8">
<img width="862" alt="er2" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/67256924/0ccfc7a2-b08f-48a0-89c2-c8a300164075">

**Comment by byshiue** [comment]
It looks the program try to find the tokenizer in `/tensorrt_llm/tokenizer` and fail. Can you check your path for tokenizer?

**Comment by konakov-ds** [comment]
Yeah, it's trying to download it from HF for some reason.
My way to the tokenizer:
tensorrtllm_backend/tensorrt_llm/tokenizer/
There's data there.
<img width="254" alt="Снимок экрана 2023-11-09 в 11 17 02" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/67256924/6aa31b73-339b-4cf3-b36d-2c0b1c473bdc">

**Comment by byshiue** [comment]
Can you share the `config.pbtxt`?

**Comment by konakov-ds** [comment]
tensorrtllm_backend/all_models/inflight_batcher_llm/preprocessing:
[
<img width="373" alt="config" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/67256924/5a1c4206-8dd5-4985-bbfa-b216e15b4b5f">
](url)

**Comment by konakov-ds** [comment]
I tried writing the full path as well, I have the tokenizer data mounted in a container, but still the error:

I1110 13:51:46.669941 830 pb_stub.cc:325] Failed to initialize Python stub: HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'tensorrtllm_backend/tensorrt_llm/tokenizer/'. Use `repo_type` argument if needed.

It tries to download tokenizer from HF.

**Comment by konakov-ds** [comment]
I used the tokenizer from HF and the problem was solved
