### ISSUE TITLE
In tensorrtllm_backend, how do I enable do sample or beam search?

### ISSUE THREAD

**Issue by yuehuayingxueluo** [triton-inference-server/tensorrtllm_backend#124]

**Comment by byshiue** [comment]
When you set the input `beam_width > 1`, it uses beam search. When `beam_width = 1`, it uses sampling depending on `top_k` and `top_p`.

**Comment by yuehuayingxueluo** [comment]
@byshiue When I try to configure beam_width, top_k, and top_p, none of them run successfully #125 #115
