### ISSUE TITLE
Why is the instacne type in inflight_batcher_llm/tensorrt_llm/configpb.txt is cpu ？

### ISSUE THREAD

**Issue by shuhaosong** [triton-inference-server/tensorrtllm_backend#127]
When I adjust the model configuration, I find that the instance type of running tensorrt_llm config.pbtxt is cpu. When I change the value to KIND_GPU, I will report an error OOM when triton server is started。
this is error message:
`[TensorRT-LLM][ERROR] 1: [defaultAllocator.cpp::allocate::20] Error Code 1: Cuda Runtime (out of memory)
[TensorRT-LLM][WARNING] Requested amount of GPU memory (4525663272 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[TensorRT-LLM][ERROR] 2: [safeDeserialize.cpp::load::264] Error Code 2: OutOfMemory (no further information)
E1114 05:30:29.694498 1123 backend_model.cc:634] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: [TensorRT-LLM][ERROR] Assertion failed: Failed to deserialize cuda engine (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:74)
1       0x7fa8527ff645 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x17645) [0x7fa8527ff645]
2       0x7fa8528d572c /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0xed72c) [0x7fa8528d572c]
3       0x7fa85284ef4e /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x66f4e) [0x7fa85284ef4e]
4       0x7fa85283ec0c /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x56c0c) [0x7fa85283ec0c]
5       0x7fa8528395f5 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x515f5) [0x7fa8528395f5]
6       0x7fa8528374db /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x4f4db) [0x7fa8528374db]
7       0x7fa85281b182 /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so(+0x33182) [0x7fa85281b182]
8       0x7fa85281b235 TRITONBACKEND_ModelInstanceInitialize + 101
9       0x7fa95b59aa86 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a4a86) [0x7fa95b59aa86]
10      0x7fa95b59bcc6 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x1a5cc6) [0x7fa95b59bcc6]
11      0x7fa95b57ec15 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x188c15) [0x7fa95b57ec15]
12      0x7fa95b57f256 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x189256) [0x7fa95b57f256]
13      0x7fa95b58b27d /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19527d) [0x7fa95b58b27d]
14      0x7fa95abf9ee8 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x99ee8) [0x7fa95abf9ee8]
15      0x7fa95b57597b /opt/tritonserver/bin/../lib/libtritonserver.so(+0x17f97b) [0x7fa95b57597b]
16      0x7fa95b585695 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x18f695) [0x7fa95b585695]
17      0x7fa95b58a50b /opt/tritonserver/bin/../lib/libtritonserver.so(+0x19450b) [0x7fa95b58a50b]
18      0x7fa95b673610 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x27d610) [0x7fa95b673610]
19      0x7fa95b676d03 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x280d03) [0x7fa95b676d03]
20      0x7fa95b7c38b2 /opt/tritonserver/bin/../lib/libtritonserver.so(+0x3cd8b2) [0x7fa95b7c38b2]
21      0x7fa95ae64253 /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7fa95ae64253]
22      0x7fa95abf4ac3 /usr/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7fa95abf4ac3]
23      0x7fa95ac85bf4 clone + 68`

basic information： Baichuan2-7B-Chat
build script：
`python build.py --model_version v2_7b --model_dir /workspace/Baichuan2-7B-Chat --dtype float16  --use_gemm_plugin float16  --use_gpt_attention_plugin float16 --max_input_len 1024 --max_output_len 256 --max_batch_size 2 --use_inflight_batching  --paged_kv_cache --world_size 4 --output_dir  /workspace/Testengine/baichuan_v2_7b_chat_fp16_ioput_1024_256_mb2/4-gpu/`
tenosrrt_llm config.pbtxt

`name: "tensorrt_llm"
backend: "tensorrtllm"
max_batch_size: 1

model_transaction_policy {
  decoupled: True
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "input_lengths"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "request_output_len"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  },
  {
    name: "end_id"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "pad_id"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "beam_width"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
    {
    name: "temperature"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_k"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_p"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "len_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "repetition_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "min_length"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "min_length"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "random_seed"
    data_type: TYPE_UINT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "streaming"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "output_log_probs"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  }
]
output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [ -1, -1 ]
  },
  {
    name: "log_probs"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_GPU
  }
]
parameters: {
  key: "max_beam_width"
  value: {
    string_value: "1"
  }
}
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value: "no"
  }
}
parameters: {
  key: "gpt_model_type"
  value: {
    string_value: "inflight_fused_batching"
  }
}
parameters: {
  key: "gpt_model_path"
  value: {
    string_value: "/workspace/model_repo/tensorrt_llm/tensorrt_llm/1"
  }
}
parameters: {
  key: "max_tokens_in_paged_kv_cache"
  value: {
    string_value: "${max_tokens_in_paged_kv_cache}"
  }
}
parameters: {
  key: "batch_scheduler_policy"
  value: {
    string_value: "${batch_scheduler_policy}"
  }
}
parameters: {
  key: "kv_cache_free_gpu_mem_fraction"
  value: {
    string_value: "${kv_cache_free_gpu_mem_fraction}"
  }
}
parameters: {
  key: "max_num_sequences"
  value: {
    string_value: "${max_num_sequences}"
  }
}
parameters: {
  key: "enable_trt_overlap"
  value: {
    string_value: "${enable_trt_overlap}"
  }
}`

请帮忙确认instance group 为KIND_CPU 时实际使用的设备

**Comment by byshiue** [comment]
We launch the instance on CPU and manage the GPU resources by the backend itself because triton does not support multi-gpu now.

**Comment by shuhaosong** [comment]
ok, thx
