### ISSUE TITLE
Proposal: restructure the README.md

### ISSUE THREAD

**Issue by wangkuiyi** [triton-inference-server/tensorrtllm_backend#133]
The content in the `README.md` file is extremely helpful – thank you!

While following the steps outlined, I noticed an inconsistency in the structure of the Table of Contents (ToC). It currently appears as follows:

```
Building the TensorRT-LLM Backend
  Option 1. Run the Docker Container
  Option 2. Build ...
  Option 3. Build ...
```

However, `Option 1` is not actually about **building** the backend; instead, it details how to **run** a pre-built release. Therefore, a more accurate structure might be moving `Option 1` to a separate section, say, `Run`.

```
Run
Build
  Option 2. Build ...
  Option 3. Build ...
```

Or more specifically:

```markdown
## Run
Starting with version 23.10, Triton has been releasing a Docker image at ... which contains everything needed to run a TensorRT-LLM model.

## Build
### Option 1. Using `build.sh`
This is the recommended approach for building ... If you are contributing to this project, this method is likely what you need.

### Option 2. Using Docker
This approach is necessary for versions of Triton prior to 23.10.
```

Would this modification be appropriate?

**Comment by juney-nvidia** [comment]
@wangkuiyi 

Sorry for replying late due to being occupied by other stuffs.

The suggestion does indeed make sense and we will make the corresponding update and refresh into the github main branch(perhaps in the next week).

Thanks
June

**Comment by juney-nvidia** [comment]
Already done and mark this as closed.
