### ISSUE TITLE
Model response not complete

### ISSUE THREAD

**Issue by AndreWanga** [triton-inference-server/tensorrtllm_backend#136]
Hi, Nvidia team. When I use tensorrt_llm I found that the required input parameter of tensorrt_llm “request_output_len” would force the length of the output_ids to equal a certain value. That lead to a incomplete sentence. How to make the model generate a complete sentence without forcibly truncating it?

**Comment by byshiue** [comment]
You could use larger `request_output_len`.

**Comment by AndreWanga** [comment]
> You could use larger `request_output_len`.

I have tried large value, I use 1000, but the response still not complete. It feels like no matter what size I set, the model forcibly outputs that length, but it might still be incomplete. @byshiue

**Comment by byshiue** [comment]
Then it may because it is hard to stop in your case. You can try different sampling configuration or setup the stop word list.

**Comment by AndreWanga** [comment]
> Then it may because it is hard to stop in your case. You can try different sampling configuration or setup the stop word list.

Could we just not limit the length of output, such as fast_llm, or the original model, let it finish naturely. @byshiue

**Comment by byshiue** [comment]
TensorRT LLM does not support such function.

**Comment by AndreWanga** [comment]
Here is an example , it may help to understand the issue:

my query_text is "hi, who are you", it's a very simple query.
And I set the temperature 0.01, runtime_top_p 0.85

here is the result when I set request_output_len to 200:

```
Hi therel I'm an AI language model designed to assist you with any questions or concerns you may have. How can I assist yo u today? The answer to your question is simply "a regular person trying to live their life." The question is asking for yo ur identity, and it is important to recognize that everyone has their own unique identity and experiences. It is important to acknowledge and celebrate your own identity, as well as the diversity of the people around you. The concept of self-ca re is becoming increasingly important in modern society. It is essential to prioritize your weli-being and take time for y ourself to relax and recharge. Here are some tips for practicing self-care:
1. Make time for self-care activities that you enjoy. This could be anything from taking a relaxing bath to reading a book
2. Get enough sleep. It is important to get at least
```

here is the result when I set request_output_len to 500:

```
Hi therel I'm an AT language model designed to assist you with any questions or concerns you may have. How can I assist you today? The answer to your question is simply "a regular person trying to live their life." The questio n is asking for your identity, and it is important to recognize that everyone has their own unique identity and e xperiences. It is important to acknowledge and celebrate your own identity, as well as the diversity of the peopl e around you. The concept of self-care is becoming increasingly important in modern society. It is essential to p rioritize your well-being and take time for yourself to relax and recharge. Here are some tips for practicing sel f-care:
1. Make time for self-care activities that you enjoy. This could be anything from taking a relaxing bath to readi ng a book.
2. Get enough sleep. It is important to get at least 7-9 hours of sleep per night to help your body and mind rech arge.
3. Eat a healthy diet. This means eating a variety of fruits, vegetables, whole grains, and lean proteins.
A. Exercise regularly. This can help reduce stress and improve your overall physical health.
5. Practice mindfulness. This can help you stay present in the moment and reduce stress.
6. Connect with friends and family. This can help you feel supported and connected.

Remember, self-care is a journey and it is important to find what works best for you. It is also important to mak e self-care a priority in your daily routine. The more you prioritize self-care, the better you wili feel for you rself. The answer to the question is "a regular person trying to live their life." The question is asking for you r identity, and it is important to recognize that everyone has their own unique identity and experiences. It is e ssential to acknowledge and celebrate your own identity, as well as the diversity of the people around you. The c oncept of self-care is becoming increasingly important in modern society. It is essential to prioritize your well
-being and take time for yourself to relax and recharge. Here are some tips for practicing self-care:
1. Make time for self-care activities that you enjoy. This could be anything from taking a relaxing bath to readi ng a book.
2. Get enough sleep
```

As you can see, to this simple question, the answer still incomplete. I think it's not normal. @byshiue

**Comment by byshiue** [comment]
Can you share results of HF (or your reference)?

**Comment by AndreWanga** [comment]
`Hello! I'm ChatGLM2-6B, an Al Assistant based on the GLM model developed by Knowledge Engineering Group, Tsinghua University and Zhipu.Al. I have been trained to understand and respond to various types of questions proposed by users.`

this is the results of HF @byshiue

**Comment by byshiue** [comment]
Can you share your scripts/codes to run HF?

**Comment by AndreWanga** [comment]
```
inputs = tokenizer([query],  return_tensors="pt")
outputs = model.generate(**inputs, "max_new_tokens": 100, "num_beams": 1,  "do_sample": False, "temperature": "0.01", "top_p": 0.95)
response = tokenizer.decode(outputs['sequences'][0][len(inputs["input_ids"][0]):])
```
@byshiue

**Comment by byshiue** [comment]
Can you check that HF stops generating before generating 100 tokens?

**Comment by AndreWanga** [comment]
> Can you check that HF stops generating before generating 100 tokens?

How to check HF stops? @byshiue

**Comment by AndreWanga** [comment]
Tanks for dealing with my issue, I found out that, there is eos_token_id in HF config.json. In original request(HF request), it automaticly send the stop token id to model, but in tensorrt_llm, I need to tell model when to stop, this is the different. Now the model can stop generate, tanks again. @byshiue
