### ISSUE TITLE
Thread [0] had error: in ensemble 'ensemble', Encountered error for requestId 498689237: Cannot process new request: Streaming mode is only supported with beam width of 1.

### ISSUE THREAD

**Issue by Juelianqvq** [triton-inference-server/tensorrtllm_backend#140]
Try to use perf_analyzer as follows deploying LLaMA2-13B with triton:

python scripts/launch_triton_server.py --world_size 2 --model_repo triton_model_repo
perf_analyzer -m ensemble -i grpc --shape "bad_words:1" --shape "max_tokens:1" --shape "stop_words:1" --shape "text_input:1" --streaming

However, I'm encountered with an error which implies the beam_width is not set correctly. 
Also, I'm a new beginner and curious about the dimension with --shape.
Can you give me some suggestions?

**Comment by byshiue** [comment]
Can you share
* the script to build engine
* the `config.pbtxt` of your backend settings

**Comment by byshiue** [comment]
I don't see you setup the beam_width when you build the engine. Can you try adding `--max_beam_width 4`?

**Comment by byshiue** [comment]
Thanks. I find the limitation in batch manager. Could you modify this issue or open another issue to require this feature?

**Comment by MuyeMikeZhang** [comment]
When I use perf_analyzer to test the performance, I meet the problem name "Thread [0] had error: Cannot send stop request without specifying a request_id". Do you know how to fix it ?
