### ISSUE TITLE
Enable more than 2048 Context length

### ISSUE THREAD

**Issue by kiransarv** [triton-inference-server/tensorrtllm_backend#141]
Hi All,

I am getting the following error after converting Llama model to TRTLLM. 
"Cannot process new request: Prompt length (5056) exceeds maximum sequence length (2048)" 
On python backend I am able to process large contexts on the same model.  How can I increase the sequence length for TRTLLM.
Is there a property ?

Thanks
Kiran

**Comment by TheCodeWrangler** [comment]
When you converted the model with trtllm, did you set the build arg `--max_input_len` to your desired lenght ( it defaults to 2048)
https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/build.py#L159

**Comment by alokkrsahu** [comment]
> Thanks.. it worked



> Thanks.. it worked

Hi, it is not working for me.

Did you make changes in the line below?
trtllm-build --checkpoint_dir /home/save/trtllm-ckpt --gpt_attention_plugin float16 --remove_input_padding enable --paged_kv_cache enable --gemm_plugin float16 --max_input_len **4096** --output_dir /home/save/trtllm-engine --use_custom_all_reduce disable


It is not working for me, please help!
