### ISSUE TITLE
segmentation fault on /generate_stream when the client tries to disconnect

### ISSUE THREAD

**Issue by anxietymonger** [triton-inference-server/tensorrtllm_backend#146]
When using /generate_stream and specifying `stream=true`, if the client tries to close the connection when the server is still generating, the server will crash on segmentation fault. 100% reproducible.

(I submitted a similar issue two weeks ago, but could find it any more)

**Comment by byshiue** [comment]
duplicate to https://github.com/triton-inference-server/tensorrtllm_backend/issues/112, close this one.

**Comment by anxietymonger** [comment]
@byshiue To my understanding, this is a different issue from #112 , though they are both related to /generate_stream. This issue incurs crash on triton server, while #112 doesn't crash, it is only a behavioral issue. Or are you implying that these two issues are caused by the same underlying problem? Appreciate if you could elaborate.

**Comment by schetlur-nv** [comment]
@anxietymonger I think https://github.com/triton-inference-server/server/issues/6576 is the issue you're referring to - the bug was root-caused to a Triton issue and has been fixed.
