### ISSUE TITLE
Feature Request: support streaming mode with beam_width > 1

### ISSUE THREAD

**Issue by Juelianqvq** [triton-inference-server/tensorrtllm_backend#150]
[https://github.com/triton-inference-server/tensorrtllm_backend/issues/140](url) @byshiue

**Comment by ncomly-nvidia** [comment]
Hi @Juelianqvq, thanks for the request! So you are looking for streaming all N beams out of the Triton backend? Including when there is BS >1? Can you help us understand your use case for this?

**Comment by SDcodehub** [comment]
Same, did not find much documentation or support on testing framework.

**Comment by matthewkotila** [comment]
I'm confused. `beam_width` is a model input, right? Are you asking how to specify a model input when running Perf Analyzer? You can specify the model input value in an input data JSON provided to Perf Analyzer, e.g.:

```
$ cat input_data.json
{
    "data": [
        {
            "beam_width": [
                1
            ]
        }
    ]
}
$ perf_analyzer -m <mode> --input-data=input_data.json
```
https://github.com/triton-inference-server/client/blob/main/src/c%2B%2B/perf_analyzer/docs/input_data.md

**Comment by meitalbensinai** [comment]
Hi, just wanted to understand that the meaning of the close status is that you added this feature in one of the last commits?
