### ISSUE TITLE
cpu is always 100% 

### ISSUE THREAD

**Issue by foricee** [triton-inference-server/tensorrtllm_backend#151]
even when there are no requests
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/1073188/bbb92e98-07df-48fa-822b-a350e815ce56)

**Comment by byshiue** [comment]
It should wait the request from client side. Do you have any concern?

**Comment by foricee** [comment]
@byshiue I am not familiar with the server-side programming. I thought that the CPU is not occupied when there are no requests, so this is a normal phenomenon, right?

**Comment by byshiue** [comment]
I guess we assign the thread to wait the request from client side. I think it is a common way to wait something from another side.
