### ISSUE TITLE
baichuan v1_7b enabled inflight_fused_batching, but got "requestId 1 is already in progress, request is ignored."

### ISSUE THREAD

**Issue by sanqianyuejia** [triton-inference-server/tensorrtllm_backend#152]
### **errors:**
```
Got completed request
Received an error from server:
[StatusCode.INTERNAL] requestId 1 is already in progress, request is ignored.
output_ids =  []
```

### **hardware:**
2 × L40S

### **triton_trt_llm docker:**
the latest code from github, and use [Option 3. Build via Docker](https://github.com/triton-inference-server/tensorrtllm_backend#option-3-build-via-docker)

### **build option:**
python build.py --model_version v1_7b --model_dir baichuan-7b-base/ --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --output_dir triton_model_repo/tensorrt_llm/1/2-gpu-inflight-batching/ --world_size 2 --paged_kv_cache --use_inflight_batching --remove_input_padding

### **request client:**
python3 inflight_batcher_llm/client/inflight_batcher_llm_client.py --request-output-len 120 --tokenizer_dir  baichuan-7b-base/

### **tensorrt_llm/config.pbtxt:**
```
model_transaction_policy {
  decoupled: False
}
parameters: {
  key: "gpt_model_type"
  value: {
    string_value: "inflight_fused_batching"
  }
}
parameters: {
  key: "gpt_model_path"
  value: {
    string_value: "/triton_model_repo/tensorrt_llm/1/2-gpu-inflight-batching/"
  }
}
```

**Any single request is ok, but when multiple requests was commited at the same time (or short interval), except the first request, anyone else got the response:**
```
Got completed request
Received an error from server:
[StatusCode.INTERNAL] requestId 1 is already in progress, request is ignored.
output_ids =  []
```

**Is there any problems in my configuration?** 

![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/3293357/0fff7d60-d543-44ee-9e04-c0a9f7bbfcea)
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/3293357/c83c6eb9-4ac5-448b-8dbe-bb1e736bed7f)

**Comment by pcastonguay** [comment]
By default, the `inflight_batcher_llm_client.py` sets a `request_id` to identify the request sent to the server. By default it's set to 1. You cannot have two in-flight requests with the same `request_id`. You can fix this by passing an empty `request_id` parameter:
```
python3 inflight_batcher_llm_client.py --tokenizer-dir <tokenizer_dir> --tokenizer-type <tokenizer_type> --request-id ""
```

**Comment by dongteng** [comment]
same question when I depolyed it on triton.When I send two requests in sequence, the second request will not start streaming back until the response to the first request is completed


`python3 build.py --hf_model_dir /root/model_repo \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir /root/Qwen/14B/trt_engines/fp16/2-gpu \
                --world_size 2 \
                --tp_size 2 \
                --paged_kv_cache  \
                --use_inflight_batching \`


`parameters: {
key: "gpt_model_type"
value: {
string_value: "inflight_batching"
}`

`curl -X POST 10.110.31.16:8001/v2/models/tensorrt_llm_bls/generate_stream \
-d '{"text_input": "<|im_start|>system\nyou are a writer <|im_end|>\n<|im_start|>user\ngive me a poem plz<|im_end|>\n<|im_start|>assistant\n", "max_tokens": 500, "bad_words": "\n", "stop_words": "", "end_id": [151643], "pad_id": [151643],"stream": true }'`
