### ISSUE TITLE
prompt template is error for chatglm2 model 

### ISSUE THREAD

**Issue by Lzhang-hub** [triton-inference-server/tensorrtllm_backend#153]
For the lastest branch main, I run build and run the tritonserver with `tritonserver --mdoel-repository=./chatglm2-6b-fp16`
and request model with 
```curl -X POST localhost:8000/v2/models/ensemble/generate -d {"text_input": "你好", "max_tokens": 20, "bad_words": "", "stop_words": ""}```

get the result :
```
[gMASK]sop 你好，我是人工智能助手。 根据问题，我们需要回答“你好”这句话的来源。
```
 `[gMASK]sop ` seems the prompt template for chatglm3. 

beside I run the TensorRTLLM run.py, the result is 
```
你好，我是人工智能助手。 根据问题，我们需要回答“人工智能助手”的定义。
```

`[gMASK]sop ` is add in the tritonserver?

**Comment by anxietymonger** [comment]
Same issue here. How to remove the EOS token in triton's reponse?

**Comment by byshiue** [comment]
Can you share the end to end reproduced steps?

**Comment by anxietymonger** [comment]
I found a workaround that specifying `skip_special_token=True` in _postprocessing function in `postprocessing/model.py`. Would you consider specifying this parameter in further releases? or expose this parameter in `config.pbtxt`?

**Comment by byshiue** [comment]
This is added in latest main branch https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/postprocessing/config.pbtxt#L84-L89.
