### ISSUE TITLE
tensorrt-llm backend not working when set multiple instance in 4 GPUs

### ISSUE THREAD

**Issue by sfireworks** [triton-inference-server/tensorrtllm_backend#166]
I run the triton docker with 4GPUs, and i want run 2 instances of my model in each GPU. 
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26211980/6da0d744-5067-47c7-a040-093f5c40c549)

I set the tensorrt-llm intance group to 2 in config.pbtxt, and then use /opt/scripts/launch_triton_server.py to lauch triton server, it shows the below errors.
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26211980/182fb274-716a-4ea1-91d1-df8038108b18)
How am i suppose to config the config.pbtxt to run 2 instances in each GPU?

**Comment by sfireworks** [comment]
And i found that the lauch script lauches the triton server with python backend, is this the cause of the errors above?
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26211980/841b5e28-1393-4b5e-ba50-e822243cb4bd)

**Comment by byshiue** [comment]
TensorRT-LLM does not support running several instances on one GPU, and you cannnot use `KIND_GPU` to control.

**Comment by sfireworks** [comment]
> TensorRT-LLM does not support running several instances on one GPU, and you cannnot use `KIND_GPU` to control.
actually, we just tried run 2 tensort-llm instances in one GPU, but we add the GPU count to 4, the lauch script report errors.

**Comment by sfireworks** [comment]
if i wanna lauch multiple tensorrt-llm instances, what method would you recommend?

**Comment by byshiue** [comment]
> if i wanna lauch multiple tensorrt-llm instances, what method would you recommend?

You could launch the server several times, but they cannot share weights.

**Comment by sfireworks** [comment]
> > if i wanna lauch multiple tensorrt-llm instances, what method would you recommend?
> 
> You could launch the server several times, but they cannot share weights.

thanks for your reply, i will try this method.

**Comment by yuanphoenix** [comment]
> > > if i wanna lauch multiple tensorrt-llm instances, what method would you recommend?
> > 
> > 
> > You could launch the server several times, but they cannot share weights.
> 
> thanks for your reply, i will try this method.


Will this not cause port conflicts?

**Comment by byshiue** [comment]
You could set different port like `--http-port 9012`. More details are showed in `tritonserver --help`.
