### ISSUE TITLE
After adding the end id, the stream output repeats the last token

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [triton-inference-server/tensorrtllm_backend#167]
tensorrtllm_backend/inflight_batcher_llm/client/end_to_end_grpc_client.py
Just add the end id
<img width="1005" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/6ec9dcff-6427-47c2-9b5e-709b431d6a36">

Non-streaming output ， only one point
<img width="1506" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/6f2c53c9-d596-4d63-97e0-d8c7f8bf45d4">

Streaming output, One more point
<img width="1508" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/0d5d6223-1b3c-4fca-bada-8f142639fc43">

I've encountered this problem before, but I haven't looked into it in depth
The latest main branch, all kind of input has this problem
Without the end id, there is no problem
I tested both llama and baichuan with this issue and suspected it was a bug

**Comment by byshiue** [comment]
I am trying to reproduce the issue but fail. Will continuge to investigate.

**Comment by callmezhangchenchenokay** [comment]
@byshiue Thanks for your hard work.

**Comment by christopher-ruan** [comment]
Encounter the very same problem here.

Using:
TensorRT-LLM: v0.6.0
tensorrtllm_backend: v0.6.0

With `end_id` added, ChatGLM3-6B & Baichuan2-13B encounter the problem (repeated last token), while Qwen14B does not.

**Comment by callmezhangchenchenokay** [comment]
Thanks for your hard work.  
I have now solved this problem temporarily through the logic control of post-processing, so it is not urgent;   
Due to the busy work, I will test it when I have time

**Comment by callmezhangchenchenokay** [comment]
In the latest version of the test no longer has this problem, 
can close

**Comment by Chevolier** [comment]
Encountered the same problem with Baichuan2-13B-Chat, which version did you use to solve the problem? Thank you! @callmezhangchenchenokay
