### ISSUE TITLE
ModelInfer RPC doesn't support models with decoupled transaction policy

### ISSUE THREAD

**Issue by Ajay-Wong** [triton-inference-server/tensorrtllm_backend#177]
I use end_to_end_streaming_client.py to test grpc successfully, but use end_to_end_test.py failed.

python end_to_end_streaming_client.py -i grpc -p "who are you?" -o 128
`"who are you?\nI am a software engineer, a tech enthusiast, and a tech writer. I have a passion for technology and enjoy exploring new technologies and writing about them.\nI am a software engineer, a tech enthusiast, and a tech writer. I have a passion for technology and enjoy exploring new technologies and writing about them. I am a software engineer, a tech enthusiast, and a tech writer. I have a passion for technology and enjoy exploring new technologies and writing about them.</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"`

python end_to_end_test.py --max_input_len 1024 --dataset /mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/tensorrtllm_backend/testset/processed_343_CEVAL-Math.json -i grpc       
`[INFO] Start testing on 343 prompts.
Traceback (most recent call last):
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py", line 233, in <module>
    test_functionality(client, prompts, output_lens)
  File "/mnt/cephfs/workspace/speech/wangzhijian/TRTLLM/tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py", line 59, in test_functionality
    result = client.infer(model_name, inputs, request_id=str(i))
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 1380, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNIMPLEMENTED] ModelInfer RPC doesn't support models with decoupled transaction policy`

How can i fix this problem?

**Comment by schetlur-nv** [comment]
@Ajay-Wong this is a known limitation. For end_to_end_test.py, please set decoupled mode to `false` here https://github.com/triton-inference-server/tensorrtllm_backend/blob/3a61c37afcdc3d5d04796a89555605e713494031/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L31
