### ISSUE TITLE
Any suggestion on setting max_tokens_in_paged_kv_cache to get a good balance of performance and memory usage?

### ISSUE THREAD

**Issue by npuichigo** [triton-inference-server/tensorrtllm_backend#183]

**Comment by byshiue** [comment]
It highly depends on your hardware, model size and problem size. Here is more introduction about memory usage https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/memory.md, hoping it is helpful.

**Comment by npuichigo** [comment]
Thanks for the info.
