### ISSUE TITLE
Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 226, Serialized Engine Version: 228)

### ISSUE THREAD

**Issue by zhaoxjmail** [triton-inference-server/tensorrtllm_backend#190]
I run:
python scripts/launch_triton_server.py --world_size=1 --model_repo=/tensorrtllm_backend/triton_model_repo
occur:
[TensorRT-LLM][ERROR] 1: [stdArchiveReader.cpp::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 226, Serialized Engine Version: 228)

I refer https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md
build  TensorRt-LLM docer and I using follow code to build:

python build.py --model_dir /code/tensorrt_llm/saved_model_1201 \
    --dtype float16 \
    --use_gemm_plugin float16 \
    --use_gpt_attention_plugin float16 \
    --output_dir ./bloom/

I using tritionserver docker version :nvcr.io/nvidia/tritonserver   23.10-trtllm-python-py3
=======================
i want to know which model is conflicting?

**Comment by Kevinddddddd** [comment]
same error. I use nvcr.io/nvidia/tritonserver 23.11-trtllm-python-py3.

**Comment by wjueyao** [comment]
@zhaoxjmail @Kevinddddddd 

rebuild engine files using v0.6.1 solved my problem

**Comment by Kevinddddddd** [comment]
> @zhaoxjmail @Kevinddddddd
> 
> rebuild engine files using v0.6.1 solved my problem

Which triton server container version do you use? 23.10 or 23.11?

**Comment by Kevinddddddd** [comment]
> > > @zhaoxjmail @Kevinddddddd
> > > rebuild engine files using v0.6.1 solved my problem
> > 
> > 
> > Which triton server container version do you use? 23.10 or 23.11?
> 
> 23.11. I followed this issue [#128 (comment)](https://github.com/triton-inference-server/tensorrtllm_backend/issues/128#event-11020523366) to rebuild engine file using v0.6.1

Thanks. I will try later.

**Comment by zhaoxjmail** [comment]
> > > @zhaoxjmail @Kevinddddddd
> > > rebuild engine files using v0.6.1 solved my problem
> > 
> > 
> > Which triton server container version do you use? 23.10 or 23.11?
> 
> 23.11. I followed this issue [#128 (comment)](https://github.com/triton-inference-server/tensorrtllm_backend/issues/128#event-11020523366) to rebuild engine file using v0.6.1

Thank you .i will try later

**Comment by likejazz** [comment]
Same here.  
Docker version(tritonserver 23.11-trtllm-python-py3) didn't work with model built with `build.py`.

**Comment by Akshat-Tripathi** [comment]
> Please also see [#194 (comment)](https://github.com/triton-inference-server/tensorrtllm_backend/issues/194#issuecomment-1846651100)
> 
> If you want to use Tritonserver container (nvcr.io/nvidia/tritonserver:23.11-trtllm-python-py3), please also use the same container to build the engine. As long as the engines are built and executed on the same version of TensorRT, it should work.
> 
> Thanks.

Is this the `nvcr.io/nvidia/tritonserver:23.11-trtllm-python-py3` container?

**Comment by kaiyux** [comment]
@Akshat-Tripathi Yes.

**Comment by kaiyux** [comment]
Closing this issue, please feel free to leave comments or open new issues if you're still seeing problems. Thanks.

**Comment by Qbuer** [comment]
This problem can be avoided if a version compatibility statement is provided.

**Comment by shireen-bean** [comment]
You can now solve this using the 24.01 released tensorrt-llm serving image released on 1/29/24 at `nvcr.io/nvidia/tritonserver:24.01-trtllm-python-py3`

**Comment by romanvelichkin** [comment]
Maybe there is a way to serialize model using specific version, similar to selection of ops version in onnx? This could save time, so we won't need to setup environment for each version.

**Comment by lix19937** [comment]
You should ensure that build and run the engine in the same enviroment.
