### ISSUE TITLE
Mistral 7b streaming mode with Chinese character ������?

### ISSUE THREAD

**Issue by moseshu** [triton-inference-server/tensorrtllm_backend#196]
tensorrtllm-triton streaming mode output chinese  character with "������" ?how to solve it?

**Comment by byshiue** [comment]
It may be because we cannot decode every id directly. Please try the tensorrt_llm_bls in latest codes.

**Comment by anxietymonger** [comment]
@byshiue When we try tensorrt_llm_bls, should we use v0.6.1 of Tensorrt-LLM with the main branch of tensorrtllm_backend? Or we need to use the main branch of Tensorrt-LLM, too?

**Comment by byshiue** [comment]
You could checkout the backend repo, and use git-submodule to update the tensorrt_llm. Different versions of backend have corresponding tensorrt_llm.

**Comment by moseshu** [comment]
> You could checkout the backend repo, and use git-submodule to update the tensorrt_llm. Different versions of backend have corresponding tensorrt_llm.

the last repo works fine.it's solved . Many thanks
