### ISSUE TITLE
NGC 23.11-trtllm-python-py3 container does not have tensort_llm backend models or the python module installed?

### ISSUE THREAD

**Issue by nikhilshandilya** [triton-inference-server/tensorrtllm_backend#216]
I assumed the `23.11-trtllm-python-py3` image was build using the [Dockerfile in the repo](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/dockerfile/Dockerfile.trt_llm_backend). Looks like thats not the case, can you confirm how to install tensorrt_llm and use this container to actually load engines? 

The documentation is not clear. Should we manually mount the https://github.com/triton-inference-server/tensorrtllm_backend repo and install both TRT-LLM and the ensemble models in the container? If so whats the point of vending the image. Just confused about the basics of using the NGC image.

**Comment by byshiue** [comment]
`23.11-trtllm-python-py3` only contains the TensorRT-LLM Triton backend. If you already prepare a engine generated by TensorRT-LLM, you could launch the service with such engine directly, you don't need to install TensorRT-LLM and TensorRT-LLM Triton backend again. Namely, the docker image `23.11-trtllm-python-py3` is only used for service, you cannot use it to prepare engine and convert model. 

You could see related shared libraries in `/opt/tritonserver/backends/tensorrtllm/`.

**Comment by nikhilshandilya** [comment]
Right so the docker only has the shared libraries in the backend folder, but the ensemble models are not in the container? We have to manually move them to the `/triton_model_repo/tensorrt_llm` folder from the docker volume?

**Comment by byshiue** [comment]
Yes. The ensemble model codes are example, so it is part of TRT LLM backend repo.

**Comment by Qbuer** [comment]
same question. In NGC 23.12-trtllm-python-py3 container , import tensorrt_llm fails ( all_models/gpt/tensorr_llm/1/model.py )。
