### ISSUE TITLE
Does this backend support the Lora model

### ISSUE THREAD

**Issue by runtianchen** [triton-inference-server/tensorrtllm_backend#218]
I fine tuned a llama-lora-model. 
How to deploy and call it in this backend.

**Comment by byshiue** [comment]
Not yet.

**Comment by ZhaoGuoXin** [comment]
Is there any plan to support this feature? Or is there any way to build engine with the lora weights?

**Comment by nandakishorej8** [comment]
Any update on the support to LORA weights?

**Comment by bjayakumar** [comment]
Following.

**Comment by byshiue** [comment]
LoRA model is supported in triton backend. [Here](https://github.com/triton-inference-server/tensorrtllm_backend/tree/ae52bce/inflight_batcher_llm#running-lora-inference-with-inflight-batching) is the document.

Close this bug.
