### ISSUE TITLE
About inflight_batcher_llm, In this mode, shouldn't requests be processed as soon as they come in

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [triton-inference-server/tensorrtllm_backend#230]
https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm/co nfig.pbtxt 
I noticed a few lines of code here like this 

```
dynamic_batching { 
    preferred_batch_size: [ ${triton_max_batch_size} ] 
    max_queue_delay_microseconds: ${max_queue_delay_microseconds} 
} 
```

I understand that setting of inflight_batcher_llm is not required. I don't understand why dynamic_batching is still set in inflight_batcher_llm. 
So I commented out dynamic_batching{/**/} 
 
I set max_batch_size=4 when converting the model. 
This is my model conversion script 
`python3 build.py --max_batch_size=4 --max_input_len=4096 --max_output_len=1024 --hf_model_dir /workspace/models/Qwen-14B-Chat/ --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --world_size 2 --remove_input_padding --use_inflight_batching --enable_context_fmha --tp_size 2 --output_dir /models/tmp`
 
postprocess/config.pbtxt,preprocess/config.pbtxt,,tensorrt_llm/config.pbtxt,tensorrt_llm_bls/config.pbtxt, In these files, max_batch_size: I force it to be 4 

I opened up 4 threads on the client ,and print  used time

```
prompts = [prompt1, prompt1, prompt1, prompt1] 
for i, ro in enumerate(prompts): 
thread = threading.Thread(target=run, args=(ro, i)) 
thread.start() 
```

Here are the results of their run 

<img width="539" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/c6604753-6f0c-47d8-91bf-e6b8588b3057">

And it turns out that for the most part they're doing it sequentially one by one.

-----------------------------------------------------------------------------------------------------------------
https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt
我注意到这里 有这样的几行代码
```
dynamic_batching {
    preferred_batch_size: [ ${triton_max_batch_size} ]
    max_queue_delay_microseconds: ${max_queue_delay_microseconds}
}
```
我理解的inflight_batcher_llm是不需要的设置这些的，我不明白在inflight_batcher_llm中为什么还会有dynamic_batching这一个设置，
因此我把dynamic_batching{ /**/ } 注释掉了

我在转换模型的时候设置 max_batch_size=4，  
postprocess/config.pbtxt,preprocess/config.pbtxt,,tensorrt_llm/config.pbtxt,tensorrt_llm_bls/config.pbtxt, 这些文件里面的max_batch_size:我都强制制定为4

这是我的模型转换脚本
`python3 build.py --max_batch_size=4 --max_input_len=4096 --max_output_len=1024 --hf_model_dir /workspace/models/Qwen-14B-Chat/ --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --world_size 2 --remove_input_padding --use_inflight_batching --enable_context_fmha --tp_size 2 --output_dir /models/tmp`

我在客户端开了4个线程，并打印它们的耗时
```
prompts = [prompt1, prompt1, prompt1, prompt1]
for i, ro in enumerate(prompts):
    thread = threading.Thread(target=run, args=(ro, i))
    thread.start()
```

下面是他们运行的结果  

<img width="539" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/c6604753-6f0c-47d8-91bf-e6b8588b3057">. 

看结果他们很大一部分情况都是是按顺序一个一个执行的.

**Comment by callmezhangchenchenokay** [comment]
I tested, output the longest 1024 tokens, need 20s 
While one process is processing, the other process can only start processing until the first process is finished

ensemble  didn't have this problem before

**Comment by callmezhangchenchenokay** [comment]
The stop_after_ms parameter (prepare_stop_signals()) does not work in tensorrt_llm_bls mode, but works in ensemble mode

**Comment by MrD005** [comment]
@callmezhangchenchenokay I am experiencing similar behavior using inflight batching

**Comment by shannonphu** [comment]
Same

**Comment by wjj19950828** [comment]
@callmezhangchenchenokay 
Have you solved this problem? I encountered the same problem using tensorrt_llm_bls

related issue https://github.com/triton-inference-server/tensorrtllm_backend/issues/257

**Comment by juney-nvidia** [comment]
@callmezhangchenchenokay 

Hi, can you share the detailed content of the `config.pbtxt` in your environment?

Also have you followed the guideline described [here](https://github.com/triton-inference-server/tensorrtllm_backend/tree/main/inflight_batcher_llm) to run the `inflight_batcher_llm` workflow?

June

**Comment by WeiboXu** [comment]
> @callmezhangchenchenokay
> 
> Hi, can you share the detailed content of the `config.pbtxt` in your environment?
> 
> And have you followed the guideline described [here](https://github.com/triton-inference-server/tensorrtllm_backend/tree/main/inflight_batcher_llm) to run the `inflight_batcher_llm` workflow?
> 
> June

same.
The config.pbtxt in tensorrt_llm is here:
name: "tensorrt_llm"
backend: "tensorrtllm"
max_batch_size: 4

model_transaction_policy {
  decoupled: true
}

# dynamic_batching {
#     preferred_batch_size: [ 4 ]
#     max_queue_delay_microseconds: 100000
# }

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
    allow_ragged_batch: true
  },
  {
    name: "input_lengths"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "request_output_len"
    data_type: TYPE_INT32
    dims: [ 1 ]
  },
  {
    name: "end_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "pad_id"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "bad_words_list"
    data_type: TYPE_INT32
    dims: [ 2, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "embedding_bias"
    data_type: TYPE_FP32
    dims: [ -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "beam_width"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "temperature"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_k"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_p"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "len_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "repetition_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "min_length"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "presence_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "random_seed"
    data_type: TYPE_UINT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "return_log_probs"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "streaming"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "prompt_embedding_table"
    data_type: TYPE_FP16
    dims: [ -1, -1 ]
    optional: true
    allow_ragged_batch: true
  },
  {
    name: "prompt_vocab_size"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  }
]
output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [ -1, -1 ]
  },
  {
    name: "sequence_length"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "cum_log_probs"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "output_log_probs"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_CPU
  }
]
parameters: {
  key: "max_beam_width"
  value: {
    string_value: "1"
  }
}
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value: "no"
  }
}
parameters: {
  key: "gpt_model_type"
  value: {
    string_value: "inflight_fused_batching"
  }
}
parameters: {
  key: "gpt_model_path"
  value: {
    string_value: "/models/trt_qwen_14b/"
  }
}
parameters: {
  key: "max_tokens_in_paged_kv_cache"
  value: {
    string_value: ""
  }
}
parameters: {
  key: "max_kv_cache_length"
  value: {
    string_value: ""
  }
}
parameters: {
  key: "batch_scheduler_policy"
  value: {
    string_value: "guaranteed_completion"
  }
}
parameters: {
  key: "kv_cache_free_gpu_mem_fraction"
  value: {
    string_value: "0.85"
  }
}
parameters: {
  key: "max_num_sequences"
  value: {
    string_value: "4"
  }
}
parameters: {
  key: "enable_trt_overlap"
  value: {
    string_value: "False"
  }
}
parameters: {
  key: "exclude_input_in_output"
  value: {
    string_value: "True"
  }
}

**Comment by schetlur-nv** [comment]
@callmezhangchenchenokay can you clarify - what was the scenario that was working ok, and what is showing serial behavior? When you try the case with completionTokens:1 totalTokens:1872, you mention it was working as expected previously but is no longer the case? Can you share which version was working correctly?
Is it possible that the preprocessor may be serializing things before it even gets to the main model - you can try setting preprocessor_instance_count to something > 1 in the preprocessor config.txt.

**Comment by callmezhangchenchenokay** [comment]
Hi！
<img width="465" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/146302419/ee40c230-60fe-4eb9-8603-8c2e43da7dc5">

-------------------------------------------------------
When I set concurrency to 4,
triton_client.async_stream_infer(“ensemble”, inputs, request_id=stream_id)
Their time is very stable, the time of each request is the same, and their overall time is time * 1
-------------------------------------------------------
When I set concurrency to 4,
triton_client.async_stream_infer(“tensorrt_llm_bls”, inputs, request_id=stream_id)
Their overall time is time * 4

**Comment by songyouwei** [comment]
see https://github.com/triton-inference-server/tensorrtllm_backend/issues/257#issuecomment-1877030030

**Comment by callmezhangchenchenokay** [comment]
> see [#257 (comment)](https://github.com/triton-inference-server/tensorrtllm_backend/issues/257#issuecomment-1877030030)
Thank you! Work out
