### ISSUE TITLE
Testing of the triton + tensorrt-llm 

### ISSUE THREAD

**Issue by SDcodehub** [triton-inference-server/tensorrtllm_backend#232]
At present ci folder have only 2 scripts, gives idea on the total latency.

Do we gave any framework or scripts available with which we can trace and compare other parameters like throughput, tokens/second, Concurrent tests etc

What are others using for the testing?
Are there any other aspect I can consider?

**Comment by kaiyux** [comment]
Here is an example to run performance `tools/inflight_batcher_llm/end_to_end_test.py`. You could refer https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/baichuan.md
