### ISSUE TITLE
rel branch, generate and generate_stream not working

### ISSUE THREAD

**Issue by MrD005** [triton-inference-server/tensorrtllm_backend#233]
when using generate endpoint it is giving
{'error': 'generate expects model to produce exactly 1 response, use generate stream for model that generates various number of responses'}

when using generate_stream endpoint it is returning empty response

**Comment by kaiyux** [comment]
Please share end to end steps to reproduce your issue.

**Comment by MrD005** [comment]
i might just got the solution that is to recompile the model using tensorRT-LLM branch

but for Clearity i will just explain all the steps

i have used tensorRT LLM - 0.5.0 to compile my LLama-70B model and yi-34b llamafied model into int4 awq quantized model.

then i use tensorrt llm backend - 0.5.0 with triton inference server to deploy my model and it is working fine for generate, generate_stream and also grpc inflight streaming as well.

but Stop words is not working in any of these 3 in 0.5.0 and i got to know that it updated in later version so i switch to rel branch and main branch for tensorRT llm backend and use my previous compiled 0.5.0 version model on the version and the above issue occurred.

inflight grpc is working fine in rel branch and main branch but ensemble is not working and stop words is still not working

**Comment by byshiue** [comment]
Thank you for the update. Do you still have question? It looks you still have issue on stop words and ensemble. Could you describe more?

**Comment by MrD005** [comment]
Yes, so after the previous message. i just recompile the model using the main branch for tensorRT LLM and tensorrt llm backend.

as i was going to use awq-4bit model i first use 0.5.0 branch to create .pt model of awq as .npz model from latest branch is not giving good responses. so after compiling the model i use tensorrt llm backend to deploy the model and now generate and generate_stream is working and sometime stop word is working fine to. But its like not all the time or not all the words are capable of stop word.

Example - Prompt 
"This the conversation between two pirated Luffy and Zoro and they are good friends
Luffy: Hey Zoro, how are you? My name is Luffy.
Zoro:"

this is my prompt and stop word is "Luffy:" so that it should stop after generate Zoro: message but it didn't stop at stop word. and when i replace stop word with "Zoro" it works but yes not worked with "Zoro:". I just want to understand is there any criteria of detemining what should be our stop word like Symbol should present or not "Zoro" worked but "Zoro:" not worked 

any other guideline or any help that would help me to solve this problem.

**Comment by byshiue** [comment]
You could check the `stop_words_id` in `model.py` of `preprocessing` and the `output_ids` in `model.py` of `postprocessing`. Sometimes, the mapping of `stop_words -> stop_words_ids` is not unique and the `output_ids` does not contains the `stop_words_ids`.

**Comment by MrD005** [comment]
@byshiue yes that is the actual problem as token that is passing in stop words id is never generated as they have different token ids
