### ISSUE TITLE
random_seed does't work

### ISSUE THREAD

**Issue by moseshu** [triton-inference-server/tensorrtllm_backend#237]
I set random_seed like below code. but it does't work. 
streaming mode, grpc,
this code is based on end_to_end_grpc_client.py
```
random_seed = random.randint(1,1000)
print(f"random_seed:{random_seed}")
random_seed_data = np.array([[random_seed]], dtype=np.uint64)
inputs = [
        prepare_tensor("text_input", input0_data, FLAGS.protocol),
        prepare_tensor("max_tokens", output0_len, FLAGS.protocol),
        prepare_tensor("stream", streaming_data, FLAGS.protocol),
        prepare_tensor("beam_width", beam_width_data, FLAGS.protocol),
        prepare_tensor("temperature", temperature_data, FLAGS.protocol),
        prepare_tensor("random_seed", random_seed_data, FLAGS.protocol),
    ]
```

**Comment by MrD005** [comment]
@moseshu you need to you top_p and top_k also so that temperature and all generation parameter should work

**Comment by moseshu** [comment]
> @moseshu you need to you top_p and top_k also so that temperature and all generation parameter should work

you mean that if top_p,top_k and temperature are fixed?
for example:
```
top_p=0.85
top_k=40
temperature=0.7
random_seed=1


But the same input text get the fixed output. 
```

**Comment by kaiyux** [comment]
When
```
top_p=0.85
top_k=40
temperature=0.7
```
Do you observer same output when you pass different random seed?

**Comment by MrD005** [comment]
@moseshu you need to pass random seed different everyone to see change in output text. use any random int generator function for that

**Comment by moseshu** [comment]
> When
> 
> ```
> top_p=0.85
> top_k=40
> temperature=0.7
> ```
> 
> Do you observer same output when you pass different random seed?

thanks ,it's addressed
