### ISSUE TITLE
tensorrt_llm model metrics are all `0` in ensemble mode 

### ISSUE THREAD

**Issue by hxer7963** [triton-inference-server/tensorrtllm_backend#238]
Docker version:
- r23.10-trtllm0.52
- r23.10-trtllm0.61

Triton setup:
- Set ensemble mode in triton inference server.

Observed anomalies:
- Pull metrics with `curl -v localhost:8002/metrics | grep -E "tensor|postprocess"`, and the metrics of tensorer_llm are all `0`, but other model metrics are normal.
<img width="756" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/21336062/4ddb6128-0119-4c49-ada5-7c5de76a5dbd">

**Comment by juney-nvidia** [comment]
@hxer7963 
Thanks for reporting this. I will discuss with the engineers to do the investigation.

June

**Comment by hxer7963** [comment]
r23.12 tritonserver fixed the bug.

Thanks.
