### ISSUE TITLE
triton v0.7.0 start error

### ISSUE THREAD

**Issue by moseshu** [triton-inference-server/tensorrtllm_backend#251]
the error is below:
[TensorRT-LLM][ERROR] Assertion failed: When KV cache block reuse is set, model has to be built with paged context FMHA support (/app/tensorrt_llm/cpp/tensorrt_llm/batch_manager/trtGptModelInflightBatching.cpp:140)

my script is 
```
python3 build.py --model_dir ${base_model}  --dtype float16 \
      --use_gpt_attention_plugin float16  \
      --use_gemm_plugin float16  \
      --output_dir "saved_model/1-gpu"  \
      --max_batch_size "32" --max_input_len 32256 --max_output_len 16384 \
      --use_rmsnorm_plugin float16  \
      --enable_context_fmha --remove_input_padding \
      --use_inflight_batching --paged_kv_cache \
      --max_num_tokens "2048"
```

which param is missed?

**Comment by byshiue** [comment]
Please try adding `--use_paged_context_fmha`.

**Comment by moseshu** [comment]
> Please try adding `--use_paged_context_fmha`.

there is no this parameter "use_paged_context_fmha" in llama/build.py

**Comment by byshiue** [comment]
Could you try again on `v0.7.1`? I can run your scripts successfully on `v0.7.1`.

**Comment by moseshu** [comment]
> use_paged_context_fmha

thanks so much. it works . I change in config.json, I will update it to v0.7.1
