### ISSUE TITLE
About name: "stop" in config.pbtxt

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [triton-inference-server/tensorrtllm_backend#252]
Want to know what this does

**Comment by juney-nvidia** [comment]
@callmezhangchenchenokay 

You don't need to set it manually and it is used to pass the "early stop" signal from client to the backend.

The corresponding option is [`--stop-after-ms`](https://github.com/triton-inference-server/tensorrtllm_backend/tree/main/inflight_batcher_llm#run-the-provided-client-to-send-a-request) , and the `stop` field will be set under-the-hood by the [inflight_batcher_llm.py](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L158).

June

**Comment by callmezhangchenchenokay** [comment]
Ok, thanks for your reply
