### ISSUE TITLE
[question] How do I add a custom c++ plugin using tensorrtllm_backend?

### ISSUE THREAD

**Issue by tbup** [triton-inference-server/tensorrtllm_backend#253]
I can't find any place to register the plugin using 'registerCreator' function.

**Comment by byshiue** [comment]
It is part of tensorrt llm instead of tensorrt llm backend. Like https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/cpp/tensorrt_llm/plugins/api/tllmPlugin.cpp#L116.
