### ISSUE TITLE
Any plan to align with NGC Triton releases?

### ISSUE THREAD

**Issue by anxietymonger** [triton-inference-server/tensorrtllm_backend#259]
It seems that new releases (i.e. v0.6.1, v0.7.0) of trt-llm backend are based on triton-server:23.10, but I'm wondering (maybe a bunch of other users as well) is this a temporary transitional solution, or the expected workflow in the foreseeable future? If it is the latter case, what is the use case of trtllm triton-server images (e.g. triton-server:23.12-trtllm-python-py3)?

From a user's POV, I really hope that we could use NGC releases directly instead of building the image by ourselves. It incurs unnecessary dependencies which more or less inflict environmental issues. Also it is not user friendly for enterprise DCs with limited internet access.

**Comment by shannonphu** [comment]
+1 I have been spending a lot of time rebuilding and debugging image versions, especially when I want to use the new releases which sometimes break my older workflow. I appreciate the active development and feature releases, just wish setting up the images was a smoother process for Triton x TRT-LLM compatibility 😄
