### ISSUE TITLE
Error occurs when Docker Build. (Option 3. Build via Docker)

### ISSUE THREAD

**Issue by KimMinSang96** [triton-inference-server/tensorrtllm_backend#262]
When I execute this "DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .", it doesn't proceed past "Built target runtime_src". Is there a way to fix this?

DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
[+] Building 1721.8s (25/34)                                                                                               docker:default
 => [internal] load .dockerignore                                                                                                    0.0s
 => => transferring context: 2B                                                                                                      0.0s
 => [internal] load build definition from Dockerfile.trt_llm_backend                                                                 0.0s
 => => transferring dockerfile: 2.39kB                                                                                               0.0s
 => [internal] load metadata for nvcr.io/nvidia/tritonserver:23.10-py3                                                               0.0s
 => [internal] load build context                                                                                                    0.5s
 => => transferring context: 875.29kB                                                                                                0.4s
 => [base 1/8] FROM nvcr.io/nvidia/tritonserver:23.10-py3                                                                            0.0s
 => CACHED [base 2/8] RUN apt-get update && apt-get install -y --no-install-recommends rapidjson-dev python-is-python3               0.0s
 => CACHED [base 3/8] COPY requirements.txt /tmp/                                                                                    0.0s
 => CACHED [base 4/8] RUN pip3 install -r /tmp/requirements.txt --extra-index-url https://pypi.ngc.nvidia.com                        0.0s
 => CACHED [base 5/8] RUN apt-get install sudo                                                                                       0.0s
 => [base 6/8] RUN apt-get install -y cmake                                                                                          3.8s
 => [base 7/8] RUN apt-get remove --purge -y tensorrt*                                                                               1.8s 
 => [base 8/8] RUN pip uninstall -y tensorrt                                                                                         1.0s 
 => [dev  1/10] COPY tensorrt_llm/docker/common/install_tensorrt.sh /tmp/                                                            0.0s 
 => [dev  2/10] RUN bash /tmp/install_tensorrt.sh && rm /tmp/install_tensorrt.sh                                                   538.4s 
 => [dev  3/10] COPY tensorrt_llm/docker/common/install_polygraphy.sh /tmp/                                                          0.1s 
 => [dev  4/10] RUN bash /tmp/install_polygraphy.sh && rm /tmp/install_polygraphy.sh                                                 5.2s 
 => [dev  5/10] COPY tensorrt_llm/docker/common/install_cmake.sh /tmp/                                                               0.1s 
 => [dev  6/10] RUN bash /tmp/install_cmake.sh && rm /tmp/install_cmake.sh                                                           8.3s 
 => [dev  7/10] COPY tensorrt_llm/docker/common/install_mpi4py.sh /tmp/                                                              0.1s 
 => [dev  8/10] RUN bash /tmp/install_mpi4py.sh && rm /tmp/install_mpi4py.sh                                                        46.9s 
 => [dev  9/10] COPY tensorrt_llm/docker/common/install_pytorch.sh install_pytorch.sh                                                0.1s 
 => [dev 10/10] RUN bash ./install_pytorch.sh pypi && rm install_pytorch.sh                                                        290.8s 
 => [trt_llm_builder 1/4] WORKDIR /app                                                                                               0.1s 
 => [trt_llm_builder 2/4] COPY scripts scripts                                                                                       0.0s 
 => [trt_llm_builder 3/4] COPY tensorrt_llm tensorrt_llm                                                                             1.6s 
 => [trt_llm_builder 4/4] RUN cd tensorrt_llm && python3 scripts/build_wheel.py --trt_root="/usr/local/tensorrt" -i -c && cd ..    823.0s 
 => => # cu.o                                                                                                                             
 => => # [100%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/weightOnlyBatchedGemv/weightOnlyBatchedGemvBs4Int8b. 
 => => # cu.o                                                                                                                            
 => => # [100%] Built target layers_src                                                                                                  
 => => # [100%] Built target common_src                                                                                                  
 => => # [100%] Built target runtime_src

**Comment by juney-nvidia** [comment]
@KimMinSang96 

Hi, which commit are you using  and what is the exact issue you want us to help with? Can you share the full build log? 

June

**Comment by KimMinSang96** [comment]
problem solived.
i thought it was an error because it took so long.
