### ISSUE TITLE
decoupled mode test fail

### ISSUE THREAD

**Issue by wangxshen** [triton-inference-server/tensorrtllm_backend#268]
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/143871924/099cfe2d-6b97-4127-9e73-05da1ed5caef)
I got fail when test in decoupled mode. what i want is streaming output, but trt-triton-server just return the last token.

**Comment by juney-nvidia** [comment]
@wangxshen 
Hi,

As @byshiue said, you can follow the doc guide firstly and if there is still issue, pls share us the concrete steps to reproduce it.

Thanks
June

**Comment by wangxshen** [comment]
> Do you following guides here https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama.md? If not, could,you take a try?

it works, The problem is that the engine is built with incorrect parameters. thx
