### ISSUE TITLE
Inflight batcher LLM models can't be used with KIND_GPU

### ISSUE THREAD

**Issue by bhavika** [triton-inference-server/tensorrtllm_backend#277]
I'm trying to deploy Llama-2-7b-chat-hf to Triton. I noticed that in the provided models for inflight_batcher_llm, the instance_group is using KIND_CPU https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/postprocessing/config.pbtxt#L94

I tried changing this to KIND_GPU but unfortunately the Triton server fails to start at this point. 

I'm using NVidia A100. Here are some screenshots for when the Triton server seems to get stuck: 

The preprocessing and postprocessing models seem to get placed on GPUs: 

<img width="1379" alt="Screenshot 2024-01-03 at 12 11 39 PM" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/4955119/264aa6a3-8dc0-4012-8c87-03127aa3f6d2">

But this is where the server gets stuck for several minutes, I killed it after waiting 10 minutes: 

<img width="1861" alt="Screenshot 2024-01-03 at 12 11 32 PM" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/4955119/315dcb25-4bd0-47f4-974a-10eee701e2a9">

Does the TensorRT-LLM backend not support KIND_GPU right now?

**Comment by uppalutkarsh** [comment]
@bhavika, There is no need of changing `KIND_CPU` to `KIND_GPU` for tensorrt engine specifically inside triton model repository, it will deploy the `backend: "tensorrtllm"` (from `config.pbtxt`) on GPU itself. Other backends follow the trivial triton serving properties.
