### ISSUE TITLE
Git Clone recursive failed

### ISSUE THREAD

**Issue by lanking520** [triton-inference-server/tensorrtllm_backend#31]
just do

```
git clone https://github.com/triton-inference-server/tensorrtllm_backend --recursive
```

Error message

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:NVIDIA/TensorRT-LLM.git' into submodule path '/home/ubuntu/test/tensorrtllm_backend/tensorrt_llm' failed
Failed to clone 'tensorrt_llm'. Retry scheduled
Cloning into '/home/ubuntu/test/tensorrtllm_backend/tensorrt_llm'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by gravitino** [comment]
please adjust the .gitmodules file by rewriting the tensorrt_llm module to https

sed -i 's/git@github.com:NVIDIA\/TensorRT-LLM.git/https:\/\/github.com\/NVIDIA\/TensorRT-LLM.git/g' .gitmodules

**Comment by aasthajh** [comment]
This issue can be resolved by adding your public ssh key to GitHub
[https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account]

**Comment by kaiyux** [comment]
Closing.

@lanking520 Please re-open if you still see the issue.
