### ISSUE TITLE
Python GIL problem when using tensorrt_llm_bls

### ISSUE THREAD

**Issue by ZihanLiao** [triton-inference-server/tensorrtllm_backend#321]
The following problem occurred when using tensorrt_llm_bls. It's hard to locate the problem, which might similar to this [problem](https://stackoverflow.com/questions/66795159/python-app-crashed-with-pyeval-restorethread-the-function-must-be-called-with)
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/54339989/971de0ff-45a6-45b3-b4b0-908f9f10dbc7)
Main execution part

`  def execute(self, requests):

        responses = []
        bls_response_sender = None

        for request in requests:

            #Get the response sender for the BLS
            if self.decoupled:
                bls_response_sender = request.get_response_sender()

            try:
                # Get the bls input tensors
                bls_input_tensors_map = self._get_bls_input_tensors_map(
                    request)

                #Check the batch dimension
                for name, tensor in bls_input_tensors_map.items():
                    batch_dim = tensor.as_numpy().shape[0]

                    if batch_dim != 1:

                        err_str = "Inflight batching backend expects requests with batch size of 1."
                        self.logger.log_error(err_str)
                        raise pb_utils.TritonModelException(err_str)

                # Create the preprocessor input tensors
                preproc_input_tensors = self._get_preproc_input_tensors(
                    bls_input_tensors_map)

                preproc_request = pb_utils.InferenceRequest(
                    model_name="preprocessing",
                    inputs=preproc_input_tensors,
                    requested_output_names=list(
                        self.preproc_output_to_trtllm_input_map.keys()))

                #Execute preprocessor
                preproc_response = preproc_request.exec()

                if preproc_response.has_error():
                    raise pb_utils.TritonModelException(
                        preproc_response.error().message())

                # Create the trtllm input tensors
                trtllm_input_tensors = self._get_trtllm_input_tensors(
                    bls_input_tensors_map, preproc_response.output_tensors())

                trtllm_request = pb_utils.InferenceRequest(
                    model_name="tensorrt_llm",
                    inputs=trtllm_input_tensors,
                    request_id="",
                    requested_output_names=list(
                        self.trtllm_output_to_postproc_input_map.keys()),)

                #Execute trtllm
                trtllm_responses = trtllm_request.exec(
                    decoupled=self.decoupled)

                if not self.decoupled:
                    trtllm_responses = [trtllm_responses]

                tokens = None

                repetition_count = 0
                max_repetition_count = 3
                #Loop over the trtllm responses
                for idx, trtllm_response in enumerate(trtllm_responses):
                    self.logger.log_info(f"Response number: {idx}")
                    if trtllm_response.has_error():
                        raise pb_utils.TritonModelException(
                            trtllm_response.error().message())

                    trtllm_output_tensors = trtllm_response.output_tensors()

                    tokens, postproc_input_tensors = self._get_postproc_input_tensors(
                        tokens, trtllm_output_tensors)
                    
                    if tokens[0, 0, -1] > 31999 or tokens[0, 0, -1] < 0: 
                        tokens[0, 0, -1] = 2
                    
                    repeated = self._check_repetition(tokens)

                    postproc_request = pb_utils.InferenceRequest(
                        model_name="postprocessing",
                        inputs=postproc_input_tensors,
                        requested_output_names=list(
                            self.postproc_output_to_bls_output_map.keys()))

                    #Execute postprocessor
                    postproc_response = postproc_request.exec()

                    if postproc_response.has_error():
                        raise pb_utils.TritonModelException(
                            postproc_response.error().message())

                    if repeated:
                        repetition_count += 1
                        if repetition_count == max_repetition_count:
                            # Create the BLS response
                            self.repetition_memory.clear()
                            self.logger.log_info(
                                f"Found repetition, repetition count = {repetition_count}"
                            )
                            self.logger.log_info(
                                f"Current tokens are {tokens}"
                            )

                            stop_input = self._prepare_stop_signals()
                            # stop_trtllm_tensor = [pb_utils.Tensor("stop", np.array([[True]], dtype=bool))]
                            # request_output_names = ["stop"]
                            # trtllm_input_tensors.append(pb_utils.Tensor("stop", np.array([[True]], dtype=bool)))
                    
                            request_output_names = list(self.trtllm_output_to_postproc_input_map.keys())
                            request_output_names.append("stop")
                            trtllm_request = pb_utils.InferenceRequest(
                                model_name="tensorrt_llm",
                                inputs=stop_input,
                                requested_output_names=request_output_names,
                                request_id="",
                            )
                            self.logger.log_info(f"Sending stop signal to tensorrt_llm....")
                            _ = trtllm_request.exec(decoupled=self.decoupled)
                            bls_response_sender.send(
                                flags=pb_utils.TRITONSERVER_RESPONSE_COMPLETE_FINAL)
                            return None
                        
                    # Create the BLS response
                    bls_output_tensors = self._get_bls_output_tensors(
                        postproc_response.output_tensors())

                    bls_response = pb_utils.InferenceResponse(
                        output_tensors=bls_output_tensors)

                    if self.decoupled:
                        bls_response_sender.send(bls_response)
                        self.logger.log_info(f"Sent a message to client")
                    else:
                        responses.append(bls_response)

                # All responses have been sent, set final flag
                if self.decoupled:
                    bls_response_sender.send(
                        flags=pb_utils.TRITONSERVER_RESPONSE_COMPLETE_FINAL)

            except Exception:

                self.logger.log_error(traceback.format_exc())
                # If encountering an error, send a response with err msg
                error_response = pb_utils.InferenceResponse(
                    output_tensors=[],
                    error=pb_utils.TritonError(traceback.format_exc()))

                if self.decoupled:
                    bls_response_sender.send(error_response)
                    bls_response_sender.send(
                        flags=pb_utils.TRITONSERVER_RESPONSE_COMPLETE_FINAL)
                else:
                    responses.append(error_response)

        self.repetition_memory.clear()
        if self.decoupled:
            return None
        else:
            assert len(responses) == len(requests)
            return responses
`
Environment: cuda 12.2, tensorrt_llm v0.6.1

**Comment by pcastonguay** [comment]
Could you please try with the latest version of TRT-LLM? Also, what version of Triton are you using?

**Comment by pcastonguay** [comment]
Also how did you launch the `tritonserver` executable?

**Comment by ZihanLiao** [comment]
> Could you please try with the latest version of TRT-LLM? Also, what version of Triton are you using?

Problem solved by using the latest docker.
