### ISSUE TITLE
Postprocessing does not work when some tensors are not returned by the model.

### ISSUE THREAD

**Issue by HishamYahya** [triton-inference-server/tensorrtllm_backend#340]
### System Info

tensorrtllm_backend commit: 6230b69c973a64f8db2763f4f9347ec77a0404e2

### Who can help?

@kaiyux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Set return_log_probs or return_context_logits or return_generation_logits to False
2. Query the ensemble or tensorrt_llm_bls generate endpoint

### Expected behavior

Returns the generated text

### actual behavior

For the ensemble endpoint: {"error":"in ensemble 'ensemble', Failed to process the request(s) for model insta│_repo/postprocessing/1/model.py 
nce 'postprocessing_0_0', message: AttributeError: 'NoneType' object has no attrib│root@29898b51710c4ef08bad80f34fbbb75b00004U:/tensorrtllm_backend# cp triton_model
ute 'as_numpy'\n\nAt:\n  /hf_models/triton_model_repo/postprocessing/1/model.py(12│_repo/ /hf_models/ -r
1): execute\n"}

For the tensorrt_llm_bls endpoint: {"error":"Traceback (most recent call last):\n  File \"/hf_models/triton_model_rep│root@29898b51710c4ef08bad80f34fbbb75b00004U:/tensorrtllm_backend# vi triton_model
o/tensorrt_llm_bls/1/model.py\", line 337, in execute\n    raise pb_utils.TritonMo│_repo/tensorrt_llm/config.pbtxt 
delException(\nc_python_backend_utils.TritonModelException: Failed to process the │root@29898b51710c4ef08bad80f34fbbb75b00004U:/tensorrtllm_backend# vi triton_model
request(s) for model instance 'postprocessing_0_0', message: AttributeError: 'None│_repo/postprocessing/1/model.py 
Type' object has no attribute 'as_numpy'\n\nAt:\n  /hf_models/triton_model_repo/po│root@29898b51710c4ef08bad80f34fbbb75b00004U:/tensorrtllm_backend# cp triton_model
stprocessing/1/model.py(121): execute\n\n"}

### additional notes

Adding default values for each of the tensors when they are not returned by the model fixes this issue.

**Comment by byshiue** [comment]
Could you refine your `actual behavior`? It looks there are many specail tokens and hard to read directly.

**Comment by HishamYahya** [comment]
@byshiue 
> Could you refine your `actual behavior`? It looks there are many specail tokens and hard to read directly.
```
E0227 09:25:36.950905 1571 model.py:355] Traceback (most recent call last):
  File "/triton_repo/tensorrt_llm_bls/1/model.py", line 333, in execute
    raise pb_utils.TritonModelException(
c_python_backend_utils.TritonModelException: Failed to process the request(s) for model instance 'postprocessing_0_0', message: AttributeError: 'NoneType' object has no attribute 'as_numpy'

At:
  /triton_repo/postprocessing/1/model.py(121): execute
```

The reason for this is that as_numpy() gets called without first checking that some optional tensors are provided:
https://github.com/triton-inference-server/tensorrtllm_backend/blob/2c8c6ae3ca4914cdd34b7576ba066e18d3b5a532/all_models/inflight_batcher_llm/postprocessing/1/model.py#L116-L125

I created a PR that does that checking and returns empty tensors when values aren't provided (#341). That is the expected behavior, right?

**Comment by byshiue** [comment]
Thank you for the report. But I cannot reproduce such issue on my side even if I set `return_log_probs` or `return_context_logits` or `return_generation_logits` to `False`. Could you share the reproduced steps (including engine building, script to send request)? Also, if you not test on latest main branch, could you take a try on latest main branch?

**Comment by ArthurChiao** [comment]
+1, and @HishamYahya 's patch #341 works for me, thanks!
