### ISSUE TITLE
tensorrrt_llm  streaming mode does not work

### ISSUE THREAD

**Issue by yjjiang11** [triton-inference-server/tensorrtllm_backend#348]
### System Info

-TensorRT-LLM b644d9aa1e94d418cbf9b1b5a03c1db6a8662b0d
-GPU A800 80GB

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. set tensorrt_llm config.pbtxt decouple to True
2. setup tensorrt-llm server based on tritonserver using https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/scripts/launch_triton_server.py 
3. send request to tensorrt-llm server by 
 python inflight_batcher_llm/client/inflight_batcher_llm_client.py --tokenizer-dir /path/to/tokenizer --prompt "hello" --streaming

### Expected behavior

LLM Server:
t0 generate TOKEN1
t1 generate TOKEN2
t3 generate TOKEN3
.....
Client:
t0 
t1 get TOKEN1
t2 get TOKEN2
.....
![1708652909605](https://github.com/triton-inference-server/tensorrtllm_backend/assets/34344716/dfff224e-dbbf-4d71-8763-95bbe390d548)

### actual behavior

![fc97c55974c98894955c46daaaeb2e0](https://github.com/triton-inference-server/tensorrtllm_backend/assets/34344716/ef320e9f-16c9-4808-b2a0-aff7cbfc52a4)

### additional notes

I replace this line https://github.com/triton-inference-server/tensorrtllm_backend/blob/2c8c6ae3ca4914cdd34b7576ba066e18d3b5a532/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L212 `print(tokens, flush=True)` -> `print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "put token in queue:", tokens, flush=True)`
add new line below:https://github.com/triton-inference-server/tensorrtllm_backend/blob/2c8c6ae3ca4914cdd34b7576ba066e18d3b5a532/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L724  `print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "get token in queue:", tokens, flush=True)`
 
after all tokens being put in queue， the client can get tokens from queue. 
the result:
![2d1fb4aa59ed2d4b9e942b272410465](https://github.com/triton-inference-server/tensorrtllm_backend/assets/34344716/4fb8726b-87b5-441d-84b8-f98711c3646f)

this https://github.com/triton-inference-server/tensorrtllm_backend/blob/2c8c6ae3ca4914cdd34b7576ba066e18d3b5a532/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L700  takes a lots time. it may help

**Comment by jaywongs** [comment]
@yjjiang11 I also encountered the same problem. Can you please tell me how you eventually solved it? Thank you!

**Comment by nuxlear** [comment]
After wandering related repositories, I found that you must set `inflight_batching` for using token streaming also, not only `decoupled=True`. 

I tested the example below documents:
https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama.md

Maybe there should be an update of documentation for others to know it.
