### ISSUE TITLE
ibtensorrt_llm_batch_manager_static.pre_cxx11.a: file format not recognized; treating as linker script

### ISSUE THREAD

**Issue by yuehuayingxueluo** [triton-inference-server/tensorrtllm_backend#38]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/50ecf468-e648-4efc-a3c1-dc4826e26108)

**When I follow the build instructions in your Readme to build the image, I encounter this problem.**

![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/a4d8ce58-6623-49ea-9df3-431a577407c4)

nvidia-smi
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/5a1c9e81-0252-4ae0-b985-234c1b424112)

nvcc
`$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0`

pip list
Package                 Version
----------------------- --------
boltons                 23.0.0
brotlipy                0.7.0
certifi                 2023.5.7
cffi                    1.15.1
charset-normalizer      2.0.4
conda                   23.5.2
conda-content-trust     0.1.3
conda-libmamba-solver   23.5.0
conda-package-handling  2.1.0
conda_package_streaming 0.8.0
cryptography            41.0.4
filelock                3.12.4
fsspec                  2023.9.2
huggingface-hub         0.17.2
idna                    3.4
jsonpatch               1.32
jsonpointer             2.1
libmambapy              1.4.1
packaging               23.0
pip                     23.1.2
pluggy                  1.0.0
pycosat                 0.6.4
pycparser               2.21
pyOpenSSL               23.2.0
PySocks                 1.7.1
PyYAML                  6.0.1
requests                2.29.0
ruamel.yaml             0.17.21
setuptools              67.8.0
six                     1.16.0
toolz                   0.12.0
tqdm                    4.65.0
typing_extensions       4.8.0
urllib3                 1.26.16
wheel                   0.38.4
zstandard               0.19.0

cmake --version
cmake version 3.16.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by byshiue** [comment]
Pls try with this to ensure the library are properly fetched to your local storage via LFS.
https://github.com/NVIDIA/TensorRT-LLM/issues/100#issuecomment-1777104351

**Comment by yuehuayingxueluo** [comment]
I have executed ‘git lfs install‘ and ’git lfs pull‘ in the tensorrtllm_backend directory, but I still get the above error.

**Comment by yuehuayingxueluo** [comment]
Do I need to run 'git lfs install' and 'git lfs pull' again under the 'tensorrt_llm/' directory?

**Comment by byshiue** [comment]
Can you check the file size of these files? It should look like
```bash
ll TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/
total 2708
drwxrwxr-x 2 bhsueh bhsueh    4096 Oct 24 13:58 ./
drwxrwxr-x 4 bhsueh bhsueh    4096 Oct 24 13:58 ../
-rw-rw-r-- 1 bhsueh bhsueh 1489814 Oct 24 13:58 libtensorrt_llm_batch_manager_static.a
-rw-rw-r-- 1 bhsueh bhsueh 1257346 Oct 24 13:58 libtensorrt_llm_batch_manager_static.pre_cxx11.a
```

**Comment by yuehuayingxueluo** [comment]
When I deleted the tensorrtllm_backend and re-git cloned it, the problem was solved
