### ISSUE TITLE
Triton supports http streaming return？

### ISSUE THREAD

**Issue by wjj19950828** [triton-inference-server/tensorrtllm_backend#41]
Hello, currently I refer to [decouple](https://github.com/triton-inference-server/tensorrtllm_backend#modify-the-model-configuration) The entire service is already running
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/19977378/d0ab8ad3-cf19-4037-9bc2-82220175e924)

I would like to ask, if I want to stream the return, can I only use the grpc method? Can the http method also stream the return? Thank you~

**Comment by byshiue** [comment]
No. We cannot use decoupled mode with http. More details and discussion are here https://github.com/triton-inference-server/server/issues/2168.
