### ISSUE TITLE
Git submodule issue

### ISSUE THREAD

**Issue by harryjulian** [triton-inference-server/tensorrtllm_backend#42]
When using the `git submodule update --init --recursive` command I kept receiving the `fatal: Could not read from remote repository.` error.

Changed `.gitmodule` to the following to make it work. Not sure if this is worth doing in the repo to avoid the error occurring for other users but thought it would be worth mentioning.

```
[submodule "tensorrt_llm"]
	path = tensorrt_llm
	url = https://github.com/NVIDIA/TensorRT-LLM.git
```

**Comment by aspctu** [comment]
https://github.com/triton-inference-server/tensorrtllm_backend/issues/31

**Comment by byshiue** [comment]
Close this bug because it is duplicated. Please re-open if you still see the issue.
