### ISSUE TITLE
tensorrt-llm serving performance is extreamly low for llama3-8b

### ISSUE THREAD

**Issue by RunningLeon** [triton-inference-server/tensorrtllm_backend#453]
### System Info

PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.28.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.107
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.54.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   43 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7742 64-Core Processor
CPU family:                      23
Model:                           49
Thread(s) per core:              1
Core(s) per socket:              64
Socket(s):                       2
Stepping:                        0
Frequency boost:                 enabled
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000

Docker Image: nvcr.io/nvidia/tritonserver:24.04-trtllm-python-py3

### Who can help?

@kaiyux

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. create docker container
```
docker create \
  --gpus=all \
  --ipc host \
  --shm-size=16g \
  --runtime nvidia \
  --network host \
  -v /home/xxx/my-projects:/projects \
  -v /mnt:/mnt \
  -v /nvme:/nvme \
  --workdir /projects \
  -e CUDA_VISIBLE_DEVICES=3 \
  nvcr.io/nvidia/tritonserver:24.04-trtllm-python-py3 tail -f /dev/null
```

2. build trtllm engine
```
export HF_LLAMA_MODEL=./llama3/Meta-Llama-3-8B-Instruct
export UNIFIED_CKPT_PATH=./workdir/llama3-fp16-convert
export ENGINE_PATH=./workdir/llama3-fp16-engine

python3 tensorrt_llm/examples/llama/convert_checkpoint.py --model_dir ${HF_LLAMA_MODEL} \
                             --output_dir ${UNIFIED_CKPT_PATH} \
                             --dtype float16

trtllm-build --checkpoint_dir ${UNIFIED_CKPT_PATH} \
             --remove_input_padding enable \
             --gpt_attention_plugin float16 \
             --context_fmha enable \
             --gemm_plugin float16 \
             --output_dir ${ENGINE_PATH} \
             --paged_kv_cache enable \
             --max_beam_width 1 \
             --max_num_tokens 1024 \
             --max_output_len 1024 \
             --max_batch_size 256 \
             --streamingllm enable \
             --strongly_typed 

```

3. start trt llm serving 

change configs
```
export HF_LLAMA_MODEL=./llama3/Meta-Llama-3-8B-Instruct
export UNIFIED_CKPT_PATH=./workdir/llama3-fp16-convert
export ENGINE_PATH=./workdir/llama3-fp16-engine

rm -rf llama_ifb

cp all_models/inflight_batcher_llm/ llama_ifb -r

# stream
python3 tools/fill_template.py -i llama_ifb/preprocessing/config.pbtxt tokenizer_dir:${HF_LLAMA_MODEL},triton_max_batch_size:256,preprocessing_instance_count:1
python3 tools/fill_template.py -i llama_ifb/postprocessing/config.pbtxt tokenizer_dir:${HF_LLAMA_MODEL},triton_max_batch_size:256,postprocessing_instance_count:1
python3 tools/fill_template.py -i llama_ifb/tensorrt_llm_bls/config.pbtxt triton_max_batch_size:256,decoupled_mode:True,bls_instance_count:1,accumulate_tokens:True
python3 tools/fill_template.py -i llama_ifb/ensemble/config.pbtxt triton_max_batch_size:256
python3 tools/fill_template.py -i llama_ifb/tensorrt_llm/config.pbtxt triton_max_batch_size:256,decoupled_mode:True,max_beam_width:1,engine_dir:${ENGINE_PATH},max_tokens_in_paged_kv_cache:2560,max_attention_window_size:2560,kv_cache_free_gpu_mem_fraction:0.5,exclude_input_in_output:True,enable_kv_cache_reuse:False,batching_strategy:inflight_batching,max_queue_delay_microseconds:0
```

launch server
```
python3 scripts/launch_triton_server.py --world_size 1 --model_repo=llama_ifb --log --log-file run.log
```

4. benchmark with vllm
```
# install vllm==v0.4.2
cd vllm
python3 benchmarks/benchmark_serving.py \
  --backend tensorrt-llm \
  --endpoint /v2/models/ensemble/generate_stream \
  --model ensemble \
  --tokenizer ./llama3/Meta-Llama-3-8B-Instruct  \
  --dataset-name sharegpt \
  --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json \
  --port 8000 \
  --trust-remote-code \
  --request-rate 7 \
  --num-prompts 1000 \
```

### Expected behavior

TTFT should be lower.

### actual behavior

results
```
Namespace(backend='tensorrt-llm', base_url=None, host='localhost', port=8100, endpoint='/v2/models/ensemble/generate_stream', dataset=None, dataset_name='sharegpt', dataset_path='/mnt/142/github-actions/resources/ShareGPT_V3_unfiltered_cleaned_split.json', model='meta-llama/Meta-Llama-3-8B-Instruct', tokenizer='/mnt/140/llama3/Meta-Llama-3-8B-Instruct', best_of=1, use_beam_search=False, num_prompts=1000, sharegpt_output_len=None, sonnet_input_len=550, sonnet_output_len=150, sonnet_prefix_len=200, request_rate=7.0, seed=0, trust_remote_code=True, disable_tqdm=False, save_result=True, metadata=None, result_dir='results-16g')
Traffic request rate: 7.0
============ Serving Benchmark Result ============
Successful requests:                     1000      
Benchmark duration (s):                  746.21    
Total input tokens:                      213987    
Total generated tokens:                  199100    
Request throughput (req/s):              1.34      
Input token throughput (tok/s):          286.76    
Output token throughput (tok/s):         266.81    
---------------Time to First Token----------------
Mean TTFT (ms):                          319691.24 
Median TTFT (ms):                        333053.11 
P99 TTFT (ms):                           592371.46 
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          14.47     
Median TPOT (ms):                        14.05     
P99 TPOT (ms):                           23.65   
```

### additional notes

Provide if necessary

**Comment by RunningLeon** [comment]
@kaiyux hi, sorry to bother you, but could you spare some time to take a look at this issue if possible?

**Comment by kimbaol** [comment]
You can try to remove "max_tokens_in_paged_kv_cache" in tensorrt_llm/config.pbtxt

**Comment by RunningLeon** [comment]
> You can try to remove "max_tokens_in_paged_kv_cache" in tensorrt_llm/config.pbtxt

@kimbaol hi, thanks for your reply. After some digging, I believe `--max_num_tokens` when build trt engine has large influence as per https://nvidia.github.io/TensorRT-LLM/performance/perf-best-practices.html#maximum-number-of-tokens.

**Comment by zhangyu68** [comment]
> You can try to remove "max_tokens_in_paged_kv_cache" in tensorrt_llm/config.pbtxt

It does become much faster after deleting this field. Why is this?

**Comment by elinx** [comment]
issue still exists in r24.09/trtllm 0.13.0, can you share your final engine build paramaters?
