### ISSUE TITLE
No 24.05-trtllm-python-py3 in NGC Repo

### ISSUE THREAD

**Issue by avianion** [triton-inference-server/tensorrtllm_backend#476]
All other images like VLLM etc are available, but not this one. What gives?

24.05-py3-min
24.05-py3-sdk
24.05-pyt-python-py3
24.05-tf2-python-py3
24.05-vllm-python-py3
24.05-py3
24.05-py3-igpu-min
24.05-py3-igpu-sdk
24.05-py3-igpu

But no
24.05-trtllm-python-py3 ??

**Comment by byshiue** [comment]
It is filed in 05/30.

**Comment by WilliamEricCheung** [comment]
Very confused, the official website (https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-05.html#rel-24-05) says that 24.05 support TensorRT-LLM release v0.10.0. In fact, after I pulled 24.05 and ran python3 -c "import tensorrt_llm", I got [TensorRT-LLM] TensorRT-LLM version: 0.9.0.
