### ISSUE TITLE
To use features in-flighting, do we have to use triton backend？

### ISSUE THREAD

**Issue by liye0626** [triton-inference-server/tensorrtllm_backend#53]
To use features in-flighting, do we have to use triton backend？If we only build TensorRT-LLM by referring to the guide, we cannot use the in-flight batching feature?

guide: https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md

**Comment by jdemouth-nvidia** [comment]
You can use in-flight batching without Triton Server but you have to plug the batch manager into your inference server/batching script as we do in the Triton backend. It’ll be easier to use the Triton Server.
