### ISSUE TITLE
Triton Inference Server 23.10 TRT-LLM image missing some libraries to load Llama

### ISSUE THREAD

**Issue by yunfeng-scale** [triton-inference-server/tensorrtllm_backend#56]
Hi, I need to add the following libraries to image 23.10-trtllm-python-py3 in order to load a Llama model:
sentencepiece
protobuf

Can you make them included by default?

Btw thanks a lot for the image and the added `/generate` API, it makes everything much easier!

**Comment by karthiknayak02** [comment]
+1 agreed

**Comment by jbkyang-nvi** [comment]
Hello, have a few questions for you:
1. What Llama model are you using? Llama or Llama2? 
2. Can you print the error message here of what you are seeing that tells you that protobuf is not installed? 
3. Are you following [Llama tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)? Did you create the engines yourself?

**Comment by yuehuayingxueluo** [comment]
> Hello, have a few questions for you, @yunfeng-scale :
> 
> 1. What Llama model are you using? Llama or Llama2?
> 2. Can you print the error message here of what you are seeing that tells you that protobuf is not installed?
> 3. Are you following [Llama tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)? Did you create the engines yourself?
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/19f6eec3-e02f-406d-b2d3-ff6b90defa6c)
"When I follow the 'Llama tutorial' and run tensorrtllm triton serve llama, if 'decoupled_mode' is set to False (streaming disabled), there are no issues with the output of 'inflight_batcher_llm_client.py'. However, if 'decoupled_mode' is set to True (streaming enabled), 'inflight_batcher_llm_client.py' only outputs one token."

'decoupled_mode' is set to False:
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/494b3dab-a6f8-4fed-9778-71982e815f9a)

'decoupled_mode' is set to True:
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/6b65a237-60fc-417f-aaf7-5dae11f2bc3a)

**Comment by jbkyang-nvi** [comment]
@yuehuayingxueluo this seem unrelated to @yunfeng-scale 's question. Can you make a new issue?

**Comment by yuehuayingxueluo** [comment]
> 3\. [Llama tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)?
@jbkyang-nvi 
OK, a new [issue](https://github.com/triton-inference-server/tensorrtllm_backend/issues/70) has been created. Please take a look at this issue.

**Comment by yunfeng-scale** [comment]
> Hello, have a few questions for you, @yunfeng-scale :
> 
> 1. What Llama model are you using? Llama or Llama2?
> 2. Can you print the error message here of what you are seeing that tells you that protobuf is not installed?
> 3. Are you following [Llama tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)? Did you create the engines yourself?

1. Llama 2 7B
2. for sentencepiece it looks like
```
I1106 22:57:34.849212 139 pb_stub.cc:325] Failed to initialize Python stub: ImportError:
LlamaTokenizer requires the SentencePiece library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/google/sentencepiece#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.


At:
  /usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py(1210): requires_backends
  /usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py(1222): __getattribute__
  /workspace/model_repo/postprocessing/1/model.py(68): initialize
```

after installing sentencepiece, protobuf error looks like
```
I1106 23:01:13.532978 559 pb_stub.cc:325] Failed to initialize Python stub: ImportError:
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.


At:
  /usr/local/lib/python3.10/dist-packages/transformers/convert_slow_tokenizer.py(43): import_protobuf
  /usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py(171): get_spm_processor
  /usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py(141): __init__
  /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py(2250): _from_pretrained
  /usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py(2017): from_pretrained
  /workspace/model_repo/postprocessing/1/model.py(68): initialize
```
3. I followed https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama to create an engine for Llama 2 7B model.

**Comment by jbkyang-nvi** [comment]
I think this is only a requirement for the client. If you want to `run.py` I believe you need to install TensorRT-LLM python packages with 
```bash
 pip install git+https://github.com/NVIDIA/TensorRT-LLM.git
```
Which also installs `sentencepiece` and `protobuf`

see: [tutorial for building engines and testing engines](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md#create-engines-for-each-model-skip-this-step-if-you-already-have-an-engine)

**Comment by yunfeng-scale** [comment]
Thanks for the pointer. The error came up when I ran
```
python3 scripts/launch_triton_server.py --world_size=1 --model_repo=/tensorrtllm_backend/triton_model_repo
```

**Comment by jbkyang-nvi** [comment]
> Thanks for the pointer. The error came up when I ran
> 
> ```
> python3 scripts/launch_triton_server.py --world_size=1 --model_repo=/tensorrtllm_backend/triton_model_repo
> ```

If you are using `--world_size=1` then does it work with
```bash
tritonserver --model-repo=/tensorrt_llm_backend/triton_model_repo
```

**Comment by yunfeng-scale** [comment]
`tritonserver --model-repo=/tensorrt_llm_backend/triton_model_repo` gives me the same result. i don't think this has anything to do with the engine since it does not take in any Python dependencies. I can see how `pip install git+https://github.com/NVIDIA/TensorRT-LLM.git` could fix it but was hoping for the official docker image to include these dependencies by default.

**Comment by jbkyang-nvi** [comment]
> `tritonserver --model-repo=/tensorrt_llm_backend/triton_model_repo` gives me the same result. i don't think this has anything to do with the engine since it does not take in any Python dependencies. I can see how `pip install git+https://github.com/NVIDIA/TensorRT-LLM.git` could fix it but was hoping for the official docker image to include these dependencies by default.

Thanks for your response. If you provide your full set of run commands I might be able to reproduce it, and determine if its necessary to change the default image's dependencies. As of now at least following the commands from the [tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md), neither `sentencepiece` nor `protobuf` is needed.

As I commented before we are trying to limit the image to strictly necessary libraries as the image size is already large.

**Comment by yunfeng-scale** [comment]
Can you try skipping `[Create Engines for each model [skip this step if you already have an engine]]` and directly invoke triton server in the container, having an engine attached as a volume? Anyways feel free to close the issue since I don't think this is major

**Comment by jbkyang-nvi** [comment]
> Can you try skipping `[Create Engines for each model [skip this step if you already have an engine]]` and directly invoke triton server in the container, having an engine attached as a volume? Anyways feel free to close the issue since I don't think this is major

yeah I did that. Obviously if I use the same container to create and run the engines I won't run into your problem since `sentencepiece` and `protobuf` would be already installed... Not sure what the problem for your case.
