### ISSUE TITLE
Invalid argument: ensemble 'ensemble' depends on 'tensorrt_llm' which has no loaded version. Model 'tensorrt_llm' loading failed with error: version 1 is at UNAVAILABLE state: Internal: unexpected error when creating modelInstanceState: [json.exception.out_of_range.403] key 'use_custom_all_reduce' not found;

### ISSUE THREAD

**Issue by seyunchoi** [triton-inference-server/tensorrtllm_backend#568]
### System Info

-GPU: A100 80G
- docker :  24.0.7

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow nvidia techical blog [link](https://developer.nvidia.com/blog/turbocharging-meta-llama-3-performance-with-nvidia-tensorrt-llm-and-nvidia-triton-inference-server/) 

I have succeed to follow Running the model step but in Deploying with the Triton Inference Server step error occur 
i have used docker images nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3 to avoid #424 issue

### Expected behavior

launch the service successfully.

### actual behavior

![image](https://github.com/user-attachments/assets/4adef154-3040-4d56-80a5-755eff6c8bb4)

### additional notes

![image](https://github.com/user-attachments/assets/f48b26e2-5168-41fd-ab5d-28c0d4aa92b7)
![image](https://github.com/user-attachments/assets/c031662b-6ef0-4002-a06f-a6aef4151ad2)

**Comment by seyunchoi** [comment]
change to version 0.11.0 and it works

**Comment by ShivamSinghal1** [comment]
Hi @seyunchoi , where to change version 0.11.0, facing the same error

**Comment by seyunchoi** [comment]
this is how i tried 
`docker run --rm --gpus all \
  --entrypoint /bin/bash \
  --ipc=host --ulimit memlock=-1 --shm-size=20g \
  --volume $(pwd):/data --workdir /data \
  --volume /docker-release/docker-luxia-package/model/:/model \
  -it nvidia/cuda:12.4.0-devel-ubuntu22.04

# inside docker
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
pip install -r examples/bloom/requirements.txt
git lfs install

#build 
python3 examples/llama/convert_checkpoint.py --model_dir /data/Meta-Llama-3-8B-Instruct \
            --output_dir ./tllm_checkpoint_1gpu_bf16 \
            --dtype bfloat16
trtllm-build --checkpoint_dir ./tllm_checkpoint_1gpu_bf16 \
            --output_dir /data/trt-Meta-Llama-3-8B-Instruct \
            --gpt_attention_plugin bfloat16 \
            --gemm_plugin bfloat16 \
            --max_batch_size 2048 \
            --max_input_len 4096 \
            --max_num_tokens 4096 \
            --multiple_profiles enable \
            --paged_kv_cache enable \
            --use_paged_context_fmha enable 
`
get out the docker

run tritonserver 
`git clone -b v0.11.0 https://github.com/triton-inference-server/tensorrtllm_backend.git
mkdir -p repo/llama3
cp -r tensorrtllm_backend/all_models/inflight_batcher_llm/* repo/llama3/
cp ./trt-Meta-Llama-3-8B-Instruct/* repo/llama3/tensorrt_llm/1/

HF_LLAMA_MODEL="/data/Meta-Llama-3-8B-Instruct"
ENGINE_PATH="/data/repo/llama3/tensorrt_llm/1"
python3 tensorrtllm_backend/tools/fill_template.py -i repo/llama3/preprocessing/config.pbtxt tokenizer_dir:${HF_LLAMA_MODEL},tokenizer_type:auto,triton_max_batch_size:2048,preprocessing_instance_count:1
python3 tensorrtllm_backend/tools/fill_template.py -i repo/llama3/postprocessing/config.pbtxt tokenizer_dir:${HF_LLAMA_MODEL},tokenizer_type:auto,triton_max_batch_size:2048,postprocessing_instance_count:8
python3 tensorrtllm_backend/tools/fill_template.py -i repo/llama3/ensemble/config.pbtxt triton_max_batch_size:2048
python3 tensorrtllm_backend/tools/fill_template.py -i repo/llama3/tensorrt_llm/config.pbtxt triton_backend:tensorrtllm,triton_max_batch_size:2048,decoupled_mode:True,max_beam_width:1,engine_dir:${ENGINE_PATH},max_tokens_in_paged_kv_cache:2560,max_attention_window_size:2560,kv_cache_free_gpu_mem_fraction:0.9,exclude_input_in_output:True,batching_strategy:inflight_fused_batching,max_queue_delay_microseconds:10000,enable_chunked_context:True,max_num_sequences:256
rm -r repo/llama3/tensorrt_llm_bls
docker run --rm -it --net host --gpus all \
  --shm-size=2g --ulimit memlock=-1 --ulimit stack=67108864 \
  -v $(pwd):/data \
  nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3 \
  tritonserver --model-repository=/data/repo/llama3 --backend-config=default-max-batch-size=2048`

**Comment by bitlhk** [comment]
**TensorRT-LLM Release 0.12.0** 
API Changes[](https://nvidia.github.io/TensorRT-LLM/release-notes.html#id14)
[BREAKING CHANGE] max_output_len is removed from trtllm-build command, if you want to limit sequence length on engine build stage, specify max_seq_len.

**[BREAKING CHANGE] The use_custom_all_reduce argument is removed from trtllm-build.**

**Comment by nhduong1203** [comment]
Hi, I have try several version of TensorRT-LLM but still got the same error. 

The procedure and my logs is almost the same as the post. 

Any help would be greatly appreciated. @bitlhk @seyunchoi 

![Image](https://github.com/user-attachments/assets/8ef23b7f-2b57-408d-bc2a-73defbe84055)

**Comment by adityarajsahu** [comment]
@seyunchoi I am getting this error, I converted the model using tensorrt_llm==0.15.0, then while trying to deploy the trtllm engine, I am getting the same error as mentioned above. How can I resolve the issue?
