### ISSUE TITLE
feature request: Expose logprob of output tokens

### ISSUE THREAD

**Issue by yunfeng-scale** [triton-inference-server/tensorrtllm_backend#58]
Hi, can you help expose logprob of output tokens? This would be helpful for our use cases.

**Comment by jdemouth-nvidia** [comment]
Hi @yunfeng-scale ,

Thanks for your request, we will take it into account and add it to our roadmap. It's not clear to me, yet, when we will have the bandwidth to add it but we will keep you posted.

Thanks,
Julien

**Comment by byshiue** [comment]
Update title to highlight "feature reuqest".

**Comment by ncomly-nvidia** [comment]
Hi @yunfeng-scale, good news!! this work has been completed & is on main! check out `return_log_probs` in the [config.pbtxt](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/ensemble/config.pbtxt#L114)
