### ISSUE TITLE
Is it possible to edit backend within config.pbtxt from python backed to tensorrtllm backen, Whisper model ?

### ISSUE THREAD

**Issue by rungrodkspeed** [triton-inference-server/tensorrtllm_backend#605]
I do this practice : https://github.com/k2-fsa/sherpa/tree/master/triton/whisper and it's good working.

I want to know if change backed parameter in config.pbtxt from python to tensorrtllm, performance maybe better ?

Do I need to change any steps in the convert whisper to tensorrtllm which can perform on tensorrtllm backend ?

This is result after change parameter backend from python to tensorrtllm: 
![image](https://github.com/user-attachments/assets/6c272a4c-135d-45ca-9540-62c1e4b45425)

P.S. I use NGC: nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3

**Comment by yuekaizhang** [comment]
See https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/whisper.md.
