### ISSUE TITLE
Failed to load llama in triton server, parsed error

### ISSUE THREAD

**Issue by GooVincent** [triton-inference-server/tensorrtllm_backend#61]
Failed to load engine in tensorrt llm backend, refer to config files in all_models/inflight_batcher_llm. It always prompts **"..parse error"** like following. attached my own config.pbtxt at last.

Please anyone suffering with the similar issue with me, how to solved this?

## run cmd
```
# tritonserver --model-repository=/tensorrtllm_backend/triton_model_repo
```

## engine location
```
$ tree -L 1 tensorrtllm_backend/triton_model_repo/tensorrt_llm/
tensorrtllm_backend/triton_model_repo/tensorrt_llm/
|-- 1
`-- config.pbtxt
```

## Error log
tritonserver --model-repository=/tensorrtllm_backend/triton_model_repo
I1030 07:31:12.979160 4933 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x7f52d0000000' with size 268435456
I1030 07:31:12.979321 4933 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I1030 07:31:12.980735 4933 model_lifecycle.cc:461] loading: preprocessing:1
I1030 07:31:12.980758 4933 model_lifecycle.cc:461] loading: tensorrt_llm:1
I1030 07:31:12.980799 4933 model_lifecycle.cc:461] loading: postprocessing:1
E1030 07:31:13.009883 4933 backend_model.cc:634] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
E1030 07:31:13.009933 4933 model_lifecycle.cc:621] failed to load 'tensorrt_llm' version 1: Internal: unexpected error when creating modelInstanceState: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
I1030 07:31:13.009940 4933 model_lifecycle.cc:756] failed to load 'tensorrt_llm'
I1030 07:31:14.560434 4933 python_be.cc:2199] TRITONBACKEND_ModelInstanceInitialize: postprocessing_0_0 (CPU device 0)
I1030 07:31:14.861963 4933 model_lifecycle.cc:818] successfully loaded 'postprocessing'
I1030 07:31:15.621445 4933 python_be.cc:2199] TRITONBACKEND_ModelInstanceInitialize: preprocessing_0_0 (CPU device 0)
I1030 07:31:16.776123 4933 model_lifecycle.cc:818] successfully loaded 'preprocessing'
I1030 07:31:16.776258 4933 server.cc:592]

## config.pbtxt

name: "tensorrt_llm"
backend: "tensorrtllm"
max_batch_size: 128

model_transaction_policy {
  decoupled: False
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]
  },
  {
    name: "input_lengths"
    data_type: TYPE_INT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "request_output_len"
    data_type: TYPE_UINT32
    dims: [ 1 ]
  },
  {
    name: "end_id"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "pad_id"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "beam_width"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "temperature"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_k"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "runtime_top_p"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "len_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "repetition_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "min_length"
    data_type: TYPE_UINT32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "presence_penalty"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "random_seed"
    data_type: TYPE_UINT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
    optional: true
  },
  {
    name: "stop"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  },
  {
    name: "streaming"
    data_type: TYPE_BOOL
    dims: [ 1 ]
    optional: true
  }
]
output [
  {
    name: "output_ids"
    data_type: TYPE_INT32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind : KIND_CPU
  }
]
parameters: {
  key: "max_beam_width"
  value: {
    string_value: "1"
  }
}
parameters: {
  key: "FORCE_CPU_ONLY_INPUT_TENSORS"
  value: {
    string_value: "no"
  }
}
parameters: {
  key: "gpt_model_type"
  value: {
    string_value: "inflight_fused_batching"
  }
}
parameters: {
  key: "gpt_model_path"
  value: {
    string_value: "/tensorrtllm_backend/triton_model_repo/tensorrt_llm"
  }
}

**Comment by amazingkmy** [comment]
@byshiue i also have a same error. plz check this issue

**Comment by kaiyux** [comment]
This error means that there is no `config.json` file found under `/tensorrtllm_backend/triton_model_repo/tensorrt_llm` as you specified for `gpt_model_path`, please check that. Thanks.

The error is not user friendly, we have noticed that, will improve in later version.

**Comment by GooVincent** [comment]
Thanks, it works now.

**Comment by yuehuayingxueluo** [comment]
> Thanks, it works now.
Sorry to disturb you, but could you please tell me how you set the 'gpt_model_path' when running the llama model? Do you use the TensorRT engines generated by GPT or the TensorRT engines generated by llama? When I try to use the TensorRT engines generated by llama, I encounter the following error
https://user-images.githubusercontent.com/26091437/279249251-def8a96a-0e56-4274-b8f2-c82e685be8b8.png

**Comment by GooVincent** [comment]
> > Thanks, it works now.
> > Sorry to disturb you, but could you please tell me how you set the 'gpt_model_path' when running the llama model? Do you use the TensorRT engines generated by GPT or the TensorRT engines generated by llama? When I try to use the TensorRT engines generated by llama, I encounter the following error
> > ![image](https://user-images.githubusercontent.com/26091437/279249251-def8a96a-0e56-4274-b8f2-c82e685be8b8.png)

I think you should build the model with the option --use_inflight_batching opened

**Comment by yuehuayingxueluo** [comment]
> > > Thanks, it works now.
> > > Sorry to disturb you, but could you please tell me how you set the 'gpt_model_path' when running the llama model? Do you use the TensorRT engines generated by GPT or the TensorRT engines generated by llama? When I try to use the TensorRT engines generated by llama, I encounter the following error
> > > ![image](https://user-images.githubusercontent.com/26091437/279249251-def8a96a-0e56-4274-b8f2-c82e685be8b8.png)
> 
> I think you should build the model with the option --use_inflight_batching opened

OK, thank you.
