### ISSUE TITLE
</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>  It's unnecessary for me 

### ISSUE THREAD

**Issue by zhanglv0209** [triton-inference-server/tensorrtllm_backend#63]
curl --location 'ip:8000/v2/models/ensemble/generate' \
--header 'Content-Type: application/json' \
--data '{"text_input": "根据主题：无人机<br>\n对下列段落进行详细的撰写：技术价值", "max_tokens": 500, "bad_words": "", "stop_words": ""}'

result:
{
    "model_name": "ensemble",
    "model_version": "1",
    "sequence_end": false,
    "sequence_id": 0,
    "sequence_start": false,
    "text_output": " 根据主题：无人机<br>\n对下列段落进行详细的撰写：技术价值与无人机应用\n\n无人机（Unmanned Aerial Vehicle，简称UAV）是一种无需人类驾驶员操作即可自主飞行的航空器。自20世纪50年代以来，无人机技术已经取得了显著的进步，如今已经成为军事、民用和科研领域的重要工具。无人机技术的价值主要体现在以下几个方面：\n\n1. 提高作战效率：无人机可以在危险的环境中执行侦查、监视和打击任务，降低人员伤亡风险。此外，无人机可以24小时不间断地执行任务，提高情报收集和处理的效率。\n\n2. 降低成本：无人机可以替代部分有人驾驶飞机，降低军事行动的成本。同时，无人机在民用领域的应用也可以降低运输、物流和监测等方面的费用。\n\n3. 提高监测精度：无人机搭载的高分辨率相机和传感器可以实时传输高清图像和数据，提高对地面目标的识别和定位精度。这对于环境监测、灾害救援、城市规划等领域具有重要的应用价值。\n\n4. 拓展科研领域：无人机技术的发展为各种科研任务提供了新的可能性。例如，无人机可以在极端环境下进行地质勘探、生物研究等任务，提高科研工作的效率和准确性。\n\n5. 促进创新：无人机技术的快速发展推动了相关领域的技术创新，如通信、导航、控制等技术的发展。这些技术的进步为无人机在各个领域的应用提供了更多的可能性。\n\n总之，无人机技术在军事、民用和科研领域具有广泛的应用前景。随着技术的不断进步，无人机将在未来发挥更大的作用，为人类带来更多的便利和价值。</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>09年12月25日\n2009年12月25日 星期五 晴 今天是圣诞节，是西方的传统节日，也是基督教徒庆祝耶稣基督诞生的日子。在这个节日里，人们会互赠礼物、举行庆祝活动，还会与家人朋友共度美好时光。\n\n在这个特殊的日子里，我决定去逛一逛商场，看看有没有什么有趣的东西可以买。在商场里，我看到了许多圣诞主题的装饰和礼品，有圣诞树、圣诞老人、圣诞帽、圣诞礼物盒等等。这些装饰和礼品都充满了节日的气氛，让人感受到了浓浓的喜庆氛围。\n\n我还看到了许多商家在促销活动中，有的商家在打折销售商品，有的商家在举办抽奖活动，还有的商家在提供优惠券。这些促销活动吸引了众多顾客，商场里人潮涌动，热闹非凡。\n\n在商场里，我还看到了许多家庭"
}

some of the result  is not help for me ,It's unnecessary for me. exp : </s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>09年12月25日\n2009年12月25日 星期五 晴 今天是圣诞节，是西方的传统节日，也是基督教徒庆祝耶稣基督诞生的日子。在这个节日里，人们会互赠礼物、举行庆祝活动，还会与家人朋友共度美好时光。\n\n在这个特殊的日子里，我决定去逛一逛商场，看看有没有什么有趣的东西可以买。在商场里，我看到了许多圣诞主题的装饰和礼品，有圣诞树、圣诞老人、圣诞帽、圣诞礼物盒等等。这些装饰和礼品都充满了节日的气氛，让人感受到了浓浓的喜庆氛围。\n\n我还看到了许多商家在促销活动中，有的商家在打折销售商品，有的商家在举办抽奖活动，还有的商家在提供优惠券。这些促销活动吸引了众多顾客，商场里人潮涌动，热闹非凡。\n\n在商场里，我还看到了许多家庭"
}

i hope some of the result do not generate. how do i process ?

**Comment by zhanglv0209** [comment]
<img width="792" alt="image" src="https://github.com/triton-inference-server/tensorrtllm_backend/assets/16017651/98713636-afe3-4e10-a0b2-cddef03ad834">

**Comment by UncleFB** [comment]
如果你用的是llama之类的模型，可以试试加个参数，"end_id": 2。

**Comment by zhanglv0209** [comment]
> 如果你用的是llama之类的模型，可以试试加个参数，"end_id": 2。

非常谢谢，加上"end_id": 2，就解决我的问题了

**Comment by kaiyux** [comment]
Closing since problem solved by adding `"end_id": 2`, thank you very much!

**Comment by xiyuecangxin** [comment]
> > 如果你用的是llama之类的模型，可以试试加个参数，"end_id": 2。
> 
> 非常谢谢，加上"end_id": 2，就解决我的问题了

url = 'http://localhost:8000/v2/models/ensemble/generate'
data = dict(
    text_input=prompt,
    parameters=dict(
        max_tokens=768,
        bad_words=[""],
        stop_words=[""],
        end_id=2,
        test="",
    )
)
t0 = time.time()
response = requests.post(url=url, json=data)
t1 = time.time()
print(response.json()["text_output"])
print(t1 - t0)

请问是在推理的时候这么加吗？为什么我的response结尾还是有一堆</s>

**Comment by zhanglv0209** [comment]
> > > 如果你用的是llama之类的模型，可以试试加个参数，"end_id": 2。
> > 
> > 
> > 非常谢谢，加上"end_id": 2，就解决我的问题了
> 
> url = 'http://localhost:8000/v2/models/ensemble/generate' data = dict( text_input=prompt, parameters=dict( max_tokens=768, bad_words=[""], stop_words=[""], end_id=2, test="", ) ) t0 = time.time() response = requests.post(url=url, json=data) t1 = time.time() print(response.json()["text_output"]) print(t1 - t0)
> 
> 请问是在推理的时候这么加吗？为什么我的response结尾还是有一堆

只是最后一堆</s>，那就是end的占位符，代码识别处理一下就可以了。

**Comment by xiyuecangxin** [comment]
> > > > 如果你用的是llama之类的模型，可以试试加个参数，"end_id": 2。
> > > 
> > > 
> > > 非常谢谢，加上"end_id": 2，就解决我的问题了
> > 
> > 
> > url = 'http://localhost:8000/v2/models/ensemble/generate' data = dict( text_input=prompt, parameters=dict( max_tokens=768, bad_words=[""], stop_words=[""], end_id=2, test="", ) ) t0 = time.time() response = requests.post(url=url, json=data) t1 = time.time() print(response.json()["text_output"]) print(t1 - t0)
> > 请问是在推理的时候这么加吗？为什么我的response结尾还是有一堆
> 
> 只是最后一堆，那就是end的占位符，代码识别处理一下就可以了。

噢噢明白了，感谢
