### ISSUE TITLE
tritonserver does not load Lora automatically

### ISSUE THREAD

**Issue by Alireza3242** [triton-inference-server/tensorrtllm_backend#641]
I run this:

```
git-lfs clone https://huggingface.co/qychen/luotuo-lora-7b-0.1
git-lfs clone https://huggingface.co/kunishou/Japanese-Alpaca-LoRA-7b-v0
BASE_LLAMA_MODEL=llama-7b-hf/

python convert_checkpoint.py --model_dir ${BASE_LLAMA_MODEL} \
                            --output_dir ./tllm_checkpoint_1gpu \
                            --dtype float16

trtllm-build --checkpoint_dir ./tllm_checkpoint_1gpu \
            --output_dir /tmp/llama_7b_with_lora_qkv/trt_engines/fp16/1-gpu/ \
            --gemm_plugin auto \
            --lora_plugin auto \
            --max_batch_size 8 \
            --max_input_len 512 \
            --max_seq_len 562 \
            --lora_dir  "luotuo-lora-7b-0.1/"\
            --max_lora_rank 8 \
            --lora_target_modules attn_q attn_k attn_v

python ../run.py --engine_dir "/tmp/llama_7b_with_lora_qkv/trt_engines/fp16/1-gpu/" \
              --max_output_len 10 \
              --tokenizer_dir ${BASE_LLAMA_MODEL} \
              --input_text "美国的首都在哪里? \n答案:" \
              --lora_task_uids 0 \
              --use_py_session --top_p 0.5 --top_k 0
```
This worked.

and then:
```
tritonserver --model-repository=/app/model_repository

curl -X POST my_ip:8000/v2/models/ensemble/generate_stream -d '{"text_input": "Hello", "max_tokens":250, "temperature":0.00001, "top_p":0.95, "top_k":1, "repetition_penalty":1.2, "stream":true, "end_id":128009, "random_seed":1, "lora_task_id": 0}'
```

get this error:
```
data: {"error":"in ensemble 'ensemble', Executor failed process requestId 2 due to the following error: LoRA task 0 not found in cache. Please send LoRA weights with request"}
```

Why run.py load Lora automatically but tritonserver does not load Lora automatically?

**Comment by byshiue** [comment]
Please refer to this document https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/lora.md. 

In run.py, we also need to load the lora weights because we view lora weights as part of input, letting user can pass their own lora weights.

**Comment by gassannov** [comment]
is any update here.
i want to use lora in triton automaticly without sending weights.

**Comment by shinesmilels** [comment]
@byshiue My lora model is larger than 2G, sending weights with input, error is 

![Image](https://github.com/user-attachments/assets/52ed9dc8-29c8-4078-b850-9509927bebda)

When I lauch tritonserver with lora_prefetch_dir in tensorrt_llm/config.pbtxt, run inflight_batcher_llm_client.py with only id, error is
 
![Image](https://github.com/user-attachments/assets/9191f488-1dc0-46a3-909b-4c9188787cbb)
tritonserver also says 

![Image](https://github.com/user-attachments/assets/05326e5a-1deb-434f-89d8-3d3566b2f46e)

 How to solve it please, can I load lora weights  when launching tritonserver?
