### ISSUE TITLE
Failed to load tensorrt_llm when using Triton 23.10

### ISSUE THREAD

**Issue by Missmiaom** [triton-inference-server/tensorrtllm_backend#66]
error:

```
failed to load 'tensorrt_llm' version 2: Invalid argument: unable to find 'tensorrtllm/model.py' for model 'tensorrt_llm', in /opt/tritonserver/backends/tensorrtllm
```

**Comment by wwnew** [comment]
you could use the image 'nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3',rather than 'nvcr.io/nvidia/tritonserver:23.10-py3'

**Comment by wwnew** [comment]
you could use the image 'nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3',rather than 'nvcr.io/nvidia/tritonserver:23.10-py3'

**Comment by Missmiaom** [comment]
Thank you so much @wwnew ，problem solved。
