### ISSUE TITLE
Why is padding_side left for llama tokenizer?

### ISSUE THREAD

**Issue by sc-gr** [triton-inference-server/tensorrtllm_backend#69]
In the example pre/postprocessing. https://github.com/triton-inference-server/tensorrtllm_backend/blob/e514b4af5ec87477b095d3ba6fe63cc7b797055f/all_models/inflight_batcher_llm/postprocessing/1/model.py#L67-L69, the padding_side is set to left for llama (and other models). Is it for some reason?

Padding_side is right for llama on HF: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/blob/main/tokenizer_config.json#L25

**Comment by byshiue** [comment]
TRT-LLM always use right padding no matter which model we use. But TRT-LLM add padding by itself, insteading of by tokenizer, you can refer https://github.com/triton-inference-server/tensorrtllm_backend/blob/e514b4af5ec87477b095d3ba6fe63cc7b797055f/all_models/inflight_batcher_llm/preprocessing/1/model.py#L174-L190.

**Comment by sc-gr** [comment]
Thanks. In other words, padding_size in hf tokenizer doesn't matter.

**Comment by byshiue** [comment]
> Thanks. In other words, padding_size in hf tokenizer doesn't matter.

For backend, that's right.

**Comment by byshiue** [comment]
Close this issue. Feel free to reopen if needed.
