### ISSUE TITLE
 if 'decoupled_mode' is set to True (streaming enabled), 'inflight_batcher_llm_client.py' only outputs one token."

### ISSUE THREAD

**Issue by yuehuayingxueluo** [triton-inference-server/tensorrtllm_backend#70]
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/19f6eec3-e02f-406d-b2d3-ff6b90defa6c)
"When I follow the ’[Llama tutorial](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md)‘ and run tensorrtllm triton serve llama, if 'decoupled_mode' is set to False (streaming disabled), there are no issues with the output of 'inflight_batcher_llm_client.py'. However, if 'decoupled_mode' is set to True (streaming enabled), 'inflight_batcher_llm_client.py' only outputs one token."

'decoupled_mode' is set to False:
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/494b3dab-a6f8-4fed-9778-71982e815f9a)

'decoupled_mode' is set to True:
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/26091437/6b65a237-60fc-417f-aaf7-5dae11f2bc3a)

**Comment by jbkyang-nvi** [comment]
How you are running the [inflight_batcher_client.py](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py) script? Are you using streaming?

**Comment by yuehuayingxueluo** [comment]
> How you are running the [inflight_batcher_client.py](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py) script? Are you using streaming?

Yes

**Comment by omer-dayan** [comment]
I ran through this as well, can you explain how you handled that?
