### ISSUE TITLE
how can I stop my model generation? stop words or any other way?

### ISSUE THREAD

**Issue by yoyopdc** [triton-inference-server/tensorrtllm_backend#82]
Hi there 
    I had load the codeLlama in tritonserver , and I passed the stop words just like fastertransformer backend before, But tensorrt did not stop. Some information in this issue.  https://github.com/NVIDIA/TensorRT-LLM/issues/90 
I tried some log and change some code, I found the action which can not stop the model maybe in inflight batch module, Am I right? Or any other way to stop the model, I think the model should stop generation when the eos come up, but not use stop words.
thx.

**Comment by byshiue** [comment]
https://github.com/triton-inference-server/tensorrtllm_backend/issues/47 is a similar issue.

**Comment by byshiue** [comment]
https://github.com/triton-inference-server/tensorrtllm_backend/issues/47 is a similar issue.

**Comment by UncleFB** [comment]
I'm having the same problem. It may be because the stop_words parameter does not work, but end_id seems to be available now. For example, if llama, you can try to pass {"end_id":2}

**Comment by yoyopdc** [comment]
> I'm having the same problem. It may be because the stop_words parameter does not work, but end_id seems to be available now. For example, if llama, you can try to pass {"end_id":2}

Thanks I think I should use end_id to do this.so the issue is closed
