### ISSUE TITLE
UNAVAILABLE: Internal: unexpected error when creating modelInstanceState: TrtGptModelInflightBatching requires GPT attention plugin with packed input and paged KV cache.

### ISSUE THREAD

**Issue by xiaocaoxu** [triton-inference-server/tensorrtllm_backend#91]
![image](https://github.com/triton-inference-server/tensorrtllm_backend/assets/42837678/a8382fec-9b40-4e94-839c-2d534025923e)
what causes this? 

GPU: NVIDIA GeForce RTX 3090
docker image: nvcr.io/nvidia/tritonserver:23.10-vllm-python-py3

**Comment by zhjunqin** [comment]
How you solve this? thanks

**Comment by xiaocaoxu** [comment]
> How you solve this? thanks

**example：**
python build.py --model_dir /models/vicuna-7b/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir /models/triton/vicuna-7b/fp16/1-gpu/ \
                --paged_kv_cache \
                --max_batch_size 1
**paged_kv_cache is necessary**
