### ISSUE TITLE
TritonInference with trt-llm when `world_size` > 1

### ISSUE THREAD

**Issue by hchoi-moveworks** [triton-inference-server/tensorrtllm_backend#96]
Hello NVIDIA team,

From `launch_triton_server.py` [1] , it seems like when we are using tensor parallelism, we simply launch N triton services. 

[1]: https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/scripts/launch_triton_server.py#L20-L32

Given that there are N running triton services, which server instance do we call for inference? 
It would be great if there is documentation on how to run inference with model parallelism . 

Please let us know if you have any pointers/ existing documentations for this!

**Comment by kamalkraj** [comment]
+1

**Comment by byshiue** [comment]
We only let the first process (main process) to receive the request from client, other process enter endless loop to wait the request sent from the main process.

**Comment by hchoi-moveworks** [comment]
Thanks @byshiue !

1) Could you point me to code that differentiates this depending on MPI rank? 
2) Do you know `where` we specify (1) engine for each rank / (2) rank id of each of these servcies?
     - in the `launch_triton_server.py` it seems like all the arguments except `shm-region-prefix-name` [1] are the same.
     - where does rank id get passed? 
     - `TensortLLM` creaates different engine per rank -- how is this specified?  [2]
     
     [1]:  https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/scripts/launch_triton_server.py#L23C50-L23C57
     [2]: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/build.py#L109-L114

**Comment by byshiue** [comment]
1. https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/inflight_batcher_llm/src/libtensorrtllm.cc#L1157-L1162
2. engine ranks are determined by mpi rank directly.

**Comment by byshiue** [comment]
Close this bug. Feel free to reopen it if needed.
